/*
    Staging tables for the NetSuite vendorCredit object, generated by
    tools/generate_netsuite_tables.py from schemas/netsuite/vendorCredit.xsd.
    Do not edit by hand: change the schema or the generator and regenerate.

    dbo.tb_Netsuite_VendorCredit                 vendorCredit

    Left out of tb_Netsuite_VendorCredit: 253 custom fields

    Existing tables are renamed to <table>_bak (constraints included) before the
    new ones are created; drop the _bak tables once loading works. Stops without
    changes if a _bak table already exists. Runs in a single transaction.
*/
SET XACT_ABORT ON;
SET NOCOUNT ON;
IF OBJECT_ID(N'tempdb..#rebuild') IS NOT NULL DROP PROCEDURE #rebuild;
GO
-- Renames an existing table to <table>_bak (constraints get a _bak suffix too),
-- so the new definition can be created without losing data.
CREATE PROCEDURE #rebuild @table sysname AS
BEGIN
    DECLARE @bak sysname = @table + N'_bak', @old sysname, @new sysname, @obj nvarchar(300), @msg nvarchar(400);
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@table), N'U') IS NULL RETURN;
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@bak), N'U') IS NOT NULL
    BEGIN
        SET @msg = N'dbo.' + @bak + N' already exists; drop or rename it first.';
        THROW 50001, @msg, 1;
    END
    SET @obj = N'dbo.' + QUOTENAME(@table);
    EXEC sys.sp_rename @objname = @obj, @newname = @bak, @objtype = N'OBJECT';
    PRINT N'Renamed  dbo.' + @table + N' -> ' + @bak;
    DECLARE con CURSOR LOCAL FAST_FORWARD FOR
        SELECT name FROM sys.objects
        WHERE parent_object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@bak)) AND type IN ('PK', 'UQ', 'D', 'C', 'F');
    OPEN con;
    FETCH NEXT FROM con INTO @old;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @new = LEFT(@old, 124) + N'_bak';
        SET @obj = N'dbo.' + QUOTENAME(@old);
        EXEC sys.sp_rename @objname = @obj, @newname = @new, @objtype = N'OBJECT';
        FETCH NEXT FROM con INTO @old;
    END
    CLOSE con;
    DEALLOCATE con;
END
GO
BEGIN TRANSACTION;

EXEC #rebuild N'tb_Netsuite_VendorCredit';
CREATE TABLE dbo.tb_Netsuite_VendorCredit (
    BPA_Origin                 nvarchar(50)     NULL,
    BPA_Direction              nvarchar(50)     NULL,
    BPA_Company                nvarchar(50)     NULL,
    BPA_EntryID                uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_VendorCredit_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID               uniqueidentifier NULL,
    BPA_Status                 int              NULL CONSTRAINT DF_tb_Netsuite_VendorCredit_Status DEFAULT ((0)),
    BPA_Reference              nvarchar(50)     NULL,
    BPA_Reference_Description  nvarchar(100)    NULL,
    BPA_Reference2             nvarchar(50)     NULL,
    BPA_Reference2_Description nvarchar(100)    NULL,
    BPA_Action                 nvarchar(1)      NULL,
    BPA_ReturnedID             nvarchar(50)     NULL,
    BPA_Syscreated             datetime         NULL CONSTRAINT DF_tb_Netsuite_VendorCredit_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified            datetime         NULL CONSTRAINT DF_tb_Netsuite_VendorCredit_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator             nvarchar(50)     NULL,
    BPA_Error                  nvarchar(max)    NULL,
    BPA_Error_Extended         nvarchar(max)    NULL,
    BPA_Description            nvarchar(255)    NULL,
    BPA_Failcount              int              NULL CONSTRAINT DF_tb_Netsuite_VendorCredit_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid           uniqueidentifier NULL,
    BPA_TaskInstanceID         int              NULL,
    BPA_TaskID                 int              NULL,
    applied                    decimal(19,4)    NULL,
    autoApply                  bit              NULL,
    billAddr1                  nvarchar(255)    NULL,
    billAddr2                  nvarchar(255)    NULL,
    billAddr3                  nvarchar(255)    NULL,
    billAddress                nvarchar(4000)   NULL,
    billAddressee              nvarchar(255)    NULL,
    billAttention              nvarchar(255)    NULL,
    billCity                   nvarchar(255)    NULL,
    billingAddress_text        nvarchar(4000)   NULL,
    billOverride               nvarchar(4000)   NULL,
    billPhone                  nvarchar(255)    NULL,
    billState                  nvarchar(255)    NULL,
    billZip                    nvarchar(255)    NULL,
    createdDate                datetime2(3)     NULL,
    dueDate                    date             NULL,
    exchangeRate               decimal(28,10)   NULL,
    externalId                 nvarchar(255)    NULL,
    id                         nvarchar(100)    NOT NULL,
    lastModifiedDate           datetime2(3)     NULL,
    memo                       nvarchar(4000)   NULL,
    prevDate                   date             NULL,
    refName                    nvarchar(255)    NULL,
    tax2Total                  decimal(19,4)    NULL,
    taxTotal                   decimal(19,4)    NULL,
    toBePrinted                bit              NULL,
    total                      decimal(19,4)    NULL,
    tranDate                   date             NULL,
    tranId                     nvarchar(255)    NULL,
    transactionNumber          nvarchar(255)    NULL,
    unapplied                  decimal(19,4)    NULL,
    userTotal                  decimal(19,4)    NULL,
    vatRegNum                  nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_VendorCredit PRIMARY KEY CLUSTERED (BPA_EntryID)
);
PRINT N'Created  dbo.tb_Netsuite_VendorCredit';

COMMIT TRANSACTION;
GO
DROP PROCEDURE #rebuild;
GO
