/*
    Staging tables for the NetSuite invoice object, generated by
    tools/generate_netsuite_tables.py from schemas/netsuite/invoice.xsd.
    Do not edit by hand: change the schema or the generator and regenerate.

    dbo.tb_Netsuite_Invoice                      invoice
    dbo.tb_Netsuite_Invoice_Item                 invoice.item.items[]   (BPA_ParentID -> parent BPA_EntryID)

    Left out of tb_Netsuite_Invoice: 60 custom fields
    Left out of tb_Netsuite_Invoice_Item: 24 custom fields

    Existing tables are renamed to <table>_bak (constraints included) before the
    new ones are created; drop the _bak tables once loading works. Stops without
    changes if a _bak table already exists. Runs in a single transaction.
*/
SET XACT_ABORT ON;
SET NOCOUNT ON;
IF OBJECT_ID(N'tempdb..#rebuild') IS NOT NULL DROP PROCEDURE #rebuild;
GO
-- Renames an existing table to <table>_bak (constraints get a _bak suffix too),
-- so the new definition can be created without losing data.
CREATE PROCEDURE #rebuild @table sysname AS
BEGIN
    DECLARE @bak sysname = @table + N'_bak', @old sysname, @new sysname, @obj nvarchar(300), @msg nvarchar(400);
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@table), N'U') IS NULL RETURN;
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@bak), N'U') IS NOT NULL
    BEGIN
        SET @msg = N'dbo.' + @bak + N' already exists; drop or rename it first.';
        THROW 50001, @msg, 1;
    END
    SET @obj = N'dbo.' + QUOTENAME(@table);
    EXEC sys.sp_rename @objname = @obj, @newname = @bak, @objtype = N'OBJECT';
    PRINT N'Renamed  dbo.' + @table + N' -> ' + @bak;
    DECLARE con CURSOR LOCAL FAST_FORWARD FOR
        SELECT name FROM sys.objects
        WHERE parent_object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@bak)) AND type IN ('PK', 'UQ', 'D', 'C', 'F');
    OPEN con;
    FETCH NEXT FROM con INTO @old;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @new = LEFT(@old, 124) + N'_bak';
        SET @obj = N'dbo.' + QUOTENAME(@old);
        EXEC sys.sp_rename @objname = @obj, @newname = @new, @objtype = N'OBJECT';
        FETCH NEXT FROM con INTO @old;
    END
    CLOSE con;
    DEALLOCATE con;
END
GO
BEGIN TRANSACTION;

EXEC #rebuild N'tb_Netsuite_Invoice';
CREATE TABLE dbo.tb_Netsuite_Invoice (
    BPA_Origin                 nvarchar(50)     NULL,
    BPA_Direction              nvarchar(50)     NULL,
    BPA_Company                nvarchar(50)     NULL,
    BPA_EntryID                uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_Invoice_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID               uniqueidentifier NULL,
    BPA_Status                 int              NULL CONSTRAINT DF_tb_Netsuite_Invoice_Status DEFAULT ((0)),
    BPA_Reference              nvarchar(50)     NULL,
    BPA_Reference_Description  nvarchar(100)    NULL,
    BPA_Reference2             nvarchar(50)     NULL,
    BPA_Reference2_Description nvarchar(100)    NULL,
    BPA_Action                 nvarchar(1)      NULL,
    BPA_ReturnedID             nvarchar(50)     NULL,
    BPA_Syscreated             datetime         NULL CONSTRAINT DF_tb_Netsuite_Invoice_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified            datetime         NULL CONSTRAINT DF_tb_Netsuite_Invoice_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator             nvarchar(50)     NULL,
    BPA_Error                  nvarchar(max)    NULL,
    BPA_Error_Extended         nvarchar(max)    NULL,
    BPA_Description            nvarchar(255)    NULL,
    BPA_Failcount              int              NULL CONSTRAINT DF_tb_Netsuite_Invoice_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid           uniqueidentifier NULL,
    BPA_TaskInstanceID         int              NULL,
    BPA_TaskID                 int              NULL,
    altShippingCost            decimal(19,4)    NULL,
    amountPaid                 decimal(19,4)    NULL,
    amountRemaining            decimal(19,4)    NULL,
    amountRemainingTotalBox    decimal(19,4)    NULL,
    billAddr1                  nvarchar(255)    NULL,
    billAddr2                  nvarchar(255)    NULL,
    billAddr3                  nvarchar(255)    NULL,
    billAddress                nvarchar(4000)   NULL,
    billAddressee              nvarchar(255)    NULL,
    billAttention              nvarchar(255)    NULL,
    billCity                   nvarchar(255)    NULL,
    billingAddress_text        nvarchar(4000)   NULL,
    billOverride               nvarchar(4000)   NULL,
    billPhone                  nvarchar(255)    NULL,
    billState                  nvarchar(255)    NULL,
    billZip                    nvarchar(255)    NULL,
    canHaveStackable           bit              NULL,
    contribPct                 nvarchar(255)    NULL,
    createdDate                datetime2(3)     NULL,
    discountAmount             decimal(19,4)    NULL,
    discountDate               date             NULL,
    discountRate               decimal(28,10)   NULL,
    discountTotal              decimal(19,4)    NULL,
    dueDate                    date             NULL,
    email                      nvarchar(255)    NULL,
    endDate                    date             NULL,
    entityTaxRegNum            nvarchar(255)    NULL,
    estGrossProfit             decimal(19,4)    NULL,
    estGrossProfitPercent      decimal(19,4)    NULL,
    estimate                   int              NULL,
    exchangeRate               decimal(28,10)   NULL,
    excludeFromGLNumbering     bit              NULL,
    externalId                 nvarchar(255)    NULL,
    fob                        nvarchar(255)    NULL,
    id                         nvarchar(100)    NOT NULL,
    lastModifiedDate           datetime2(3)     NULL,
    linkedTrackingNumbers      nvarchar(4000)   NULL,
    memo                       nvarchar(4000)   NULL,
    message                    nvarchar(4000)   NULL,
    oppcreatedfrom             nvarchar(255)    NULL,
    oppcreatedfromtitle        nvarchar(255)    NULL,
    originator                 nvarchar(255)    NULL,
    otherRefNum                nvarchar(255)    NULL,
    overrideInstallments       bit              NULL,
    paymentlink                nvarchar(255)    NULL,
    prevDate                   date             NULL,
    previousOpportunity        nvarchar(255)    NULL,
    prevRep                    int              NULL,
    refName                    nvarchar(255)    NULL,
    salesEffectiveDate         date             NULL,
    shipAddress                nvarchar(4000)   NULL,
    shipDate                   date             NULL,
    shipIsResidential          bit              NULL,
    shipOverride               bit              NULL,
    shippingAddress_text       nvarchar(4000)   NULL,
    shippingCost               decimal(19,4)    NULL,
    shippingCostOverridden     bit              NULL,
    shippingTaxAmount          decimal(19,4)    NULL,
    startDate                  date             NULL,
    subsidiaryTaxRegNum        nvarchar(255)    NULL,
    subtotal                   decimal(19,4)    NULL,
    taxDetailsOverride         bit              NULL,
    taxPointDate               date             NULL,
    taxPointDateOverride       bit              NULL,
    taxRegOverride             bit              NULL,
    taxTotal                   decimal(19,4)    NULL,
    toBeEmailed                bit              NULL,
    toBeFaxed                  bit              NULL,
    toBePrinted                bit              NULL,
    total                      decimal(19,4)    NULL,
    totalAfterTaxes            decimal(19,4)    NULL,
    totalCostEstimate          decimal(19,4)    NULL,
    trackingNumbers            nvarchar(4000)   NULL,
    tranDate                   date             NULL,
    tranId                     nvarchar(255)    NULL,
    entityId                   nvarchar(255)    NULL,
    entityRefName              nvarchar(255)    NULL,
    locationId                 nvarchar(255)    NULL,
    locationRefName            nvarchar(255)    NULL,
    statusId                   nvarchar(255)    NULL,
    statusRefName              nvarchar(255)    NULL,
    currencyId                 nvarchar(255)    NULL,
    currencyRefName            nvarchar(255)    NULL,
    subsidiaryId               nvarchar(255)    NULL,
    subsidiaryRefName          nvarchar(255)    NULL,
    postingPeriodId            nvarchar(255)    NULL,
    postingPeriodRefName       nvarchar(255)    NULL,
    accountId                  nvarchar(255)    NULL,
    accountRefName             nvarchar(255)    NULL,
    termsId                    nvarchar(255)    NULL,
    termsRefName               nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_Invoice PRIMARY KEY CLUSTERED (BPA_EntryID)
);
PRINT N'Created  dbo.tb_Netsuite_Invoice';

EXEC #rebuild N'tb_Netsuite_Invoice_Item';
CREATE TABLE dbo.tb_Netsuite_Invoice_Item (
    BPA_Origin                 nvarchar(50)     NULL,
    BPA_Direction              nvarchar(50)     NULL,
    BPA_Company                nvarchar(50)     NULL,
    BPA_EntryID                uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_Invoice_Item_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID               uniqueidentifier NULL,
    BPA_Status                 int              NULL CONSTRAINT DF_tb_Netsuite_Invoice_Item_Status DEFAULT ((0)),
    BPA_Reference              nvarchar(50)     NULL,
    BPA_Reference_Description  nvarchar(100)    NULL,
    BPA_Reference2             nvarchar(50)     NULL,
    BPA_Reference2_Description nvarchar(100)    NULL,
    BPA_Action                 nvarchar(1)      NULL,
    BPA_ReturnedID             nvarchar(50)     NULL,
    BPA_Syscreated             datetime         NULL CONSTRAINT DF_tb_Netsuite_Invoice_Item_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified            datetime         NULL CONSTRAINT DF_tb_Netsuite_Invoice_Item_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator             nvarchar(50)     NULL,
    BPA_Error                  nvarchar(max)    NULL,
    BPA_Error_Extended         nvarchar(max)    NULL,
    BPA_Description            nvarchar(255)    NULL,
    BPA_Failcount              int              NULL CONSTRAINT DF_tb_Netsuite_Invoice_Item_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid           uniqueidentifier NULL,
    BPA_TaskInstanceID         int              NULL,
    BPA_TaskID                 int              NULL,
    amount                     decimal(19,4)    NULL,
    costEstimate               decimal(19,4)    NULL,
    costEstimateRate           decimal(28,10)   NULL,
    description                nvarchar(4000)   NULL,
    estGrossProfit             decimal(19,4)    NULL,
    estGrossProfitPercent      decimal(19,4)    NULL,
    excludeFromRateRequest     bit              NULL,
    initOqpBucket              nvarchar(255)    NULL,
    isClosed                   bit              NULL,
    isOpen                     bit              NULL,
    line                       int              NULL,
    linked                     bit              NULL,
    marginal                   bit              NULL,
    minQty                     decimal(28,10)   NULL,
    options                    nvarchar(4000)   NULL,
    oqpBucket                  nvarchar(255)    NULL,
    orderLine                  int              NULL,
    printItems                 bit              NULL,
    processedByRevCommit       bit              NULL,
    quantity                   decimal(28,10)   NULL,
    quantityAvailable          decimal(28,10)   NULL,
    quantityCommitted          decimal(28,10)   NULL,
    quantityOnHand             decimal(28,10)   NULL,
    rate                       decimal(28,10)   NULL,
    rateSchedule               nvarchar(255)    NULL,
    refName                    nvarchar(255)    NULL,
    revrec_recurrencetype      nvarchar(255)    NULL,
    taxAmount                  decimal(19,4)    NULL,
    taxDetailsReference        nvarchar(255)    NULL,
    units                      nvarchar(255)    NULL,
    vsoeAllocation             decimal(19,4)    NULL,
    vsoeAmount                 decimal(19,4)    NULL,
    vsoeIsEstimate             bit              NULL,
    itemId                     nvarchar(255)    NULL,
    itemRefName                nvarchar(255)    NULL,
    departmentId               nvarchar(255)    NULL,
    departmentRefName          nvarchar(255)    NULL,
    classId                    nvarchar(255)    NULL,
    classRefName               nvarchar(255)    NULL,
    locationId                 nvarchar(255)    NULL,
    locationRefName            nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_Invoice_Item PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_Invoice_Item_ParentID ON dbo.tb_Netsuite_Invoice_Item (BPA_ParentID);
PRINT N'Created  dbo.tb_Netsuite_Invoice_Item';

COMMIT TRANSACTION;
GO
DROP PROCEDURE #rebuild;
GO
