/*
    Staging tables for the NetSuite account object, generated by
    tools/generate_netsuite_tables.py from schemas/netsuite/account.xsd.
    Do not edit by hand: change the schema or the generator and regenerate.

    dbo.tb_Netsuite_Account                      account

    Left out of tb_Netsuite_Account: 2 custom fields, subsidiary (no items)

    Existing tables are renamed to <table>_bak (constraints included) before the
    new ones are created; drop the _bak tables once loading works. Stops without
    changes if a _bak table already exists. Runs in a single transaction.
*/
SET XACT_ABORT ON;
SET NOCOUNT ON;
IF OBJECT_ID(N'tempdb..#rebuild') IS NOT NULL DROP PROCEDURE #rebuild;
GO
-- Renames an existing table to <table>_bak (constraints get a _bak suffix too),
-- so the new definition can be created without losing data.
CREATE PROCEDURE #rebuild @table sysname AS
BEGIN
    DECLARE @bak sysname = @table + N'_bak', @old sysname, @new sysname, @obj nvarchar(300), @msg nvarchar(400);
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@table), N'U') IS NULL RETURN;
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@bak), N'U') IS NOT NULL
    BEGIN
        SET @msg = N'dbo.' + @bak + N' already exists; drop or rename it first.';
        THROW 50001, @msg, 1;
    END
    SET @obj = N'dbo.' + QUOTENAME(@table);
    EXEC sys.sp_rename @objname = @obj, @newname = @bak, @objtype = N'OBJECT';
    PRINT N'Renamed  dbo.' + @table + N' -> ' + @bak;
    DECLARE con CURSOR LOCAL FAST_FORWARD FOR
        SELECT name FROM sys.objects
        WHERE parent_object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@bak)) AND type IN ('PK', 'UQ', 'D', 'C', 'F');
    OPEN con;
    FETCH NEXT FROM con INTO @old;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @new = LEFT(@old, 124) + N'_bak';
        SET @obj = N'dbo.' + QUOTENAME(@old);
        EXEC sys.sp_rename @objname = @obj, @newname = @new, @objtype = N'OBJECT';
        FETCH NEXT FROM con INTO @old;
    END
    CLOSE con;
    DEALLOCATE con;
END
GO
BEGIN TRANSACTION;

EXEC #rebuild N'tb_Netsuite_Account';
CREATE TABLE dbo.tb_Netsuite_Account (
    BPA_Origin                   nvarchar(50)     NULL,
    BPA_Direction                nvarchar(50)     NULL,
    BPA_Company                  nvarchar(50)     NULL,
    BPA_EntryID                  uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_Account_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                 uniqueidentifier NULL,
    BPA_Status                   int              NULL CONSTRAINT DF_tb_Netsuite_Account_Status DEFAULT ((0)),
    BPA_Reference                nvarchar(50)     NULL,
    BPA_Reference_Description    nvarchar(100)    NULL,
    BPA_Reference2               nvarchar(50)     NULL,
    BPA_Reference2_Description   nvarchar(100)    NULL,
    BPA_Action                   nvarchar(1)      NULL,
    BPA_ReturnedID               nvarchar(50)     NULL,
    BPA_Syscreated               datetime         NULL CONSTRAINT DF_tb_Netsuite_Account_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified              datetime         NULL CONSTRAINT DF_tb_Netsuite_Account_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator               nvarchar(50)     NULL,
    BPA_Error                    nvarchar(max)    NULL,
    BPA_Error_Extended           nvarchar(max)    NULL,
    BPA_Description              nvarchar(255)    NULL,
    BPA_Failcount                int              NULL CONSTRAINT DF_tb_Netsuite_Account_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid             uniqueidentifier NULL,
    BPA_TaskInstanceID           int              NULL,
    BPA_TaskID                   int              NULL,
    accountSearchDisplayName     nvarchar(255)    NULL,
    accountSearchDisplayNameCopy nvarchar(255)    NULL,
    acctName                     nvarchar(255)    NULL,
    acctNumber                   nvarchar(255)    NULL,
    availableBalance             decimal(19,4)    NULL,
    curDocNum                    int              NULL,
    description                  nvarchar(4000)   NULL,
    displayNameWithHierarchy     nvarchar(255)    NULL,
    eliminate                    bit              NULL,
    externalId                   nvarchar(255)    NULL,
    fullName                     nvarchar(255)    NULL,
    id                           nvarchar(100)    NOT NULL,
    includeChildren              bit              NULL,
    inventory                    bit              NULL,
    isInactive                   bit              NULL,
    isSummary                    bit              NULL,
    lastModifiedDate             datetime2(3)     NULL,
    openingBalance               decimal(19,4)    NULL,
    reconcileWithMatching        bit              NULL,
    refName                      nvarchar(255)    NULL,
    revalue                      bit              NULL,
    sBankCompanyId               nvarchar(255)    NULL,
    sBankName                    nvarchar(255)    NULL,
    sBankRoutingNumber           nvarchar(255)    NULL,
    tranDate                     date             NULL,
    unit                         nvarchar(255)    NULL,
    currencyId                   nvarchar(255)    NULL,
    currencyRefName              nvarchar(255)    NULL,
    acctTypeId                   nvarchar(255)    NULL,
    acctTypeRefName              nvarchar(255)    NULL,
    sSpecAcctId                  nvarchar(255)    NULL,
    sSpecAcctRefName             nvarchar(255)    NULL,
    parentId                     nvarchar(255)    NULL,
    parentRefName                nvarchar(255)    NULL,
    classId                      nvarchar(255)    NULL,
    classRefName                 nvarchar(255)    NULL,
    departmentId                 nvarchar(255)    NULL,
    departmentRefName            nvarchar(255)    NULL,
    locationId                   nvarchar(255)    NULL,
    locationRefName              nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_Account PRIMARY KEY CLUSTERED (BPA_EntryID)
);
PRINT N'Created  dbo.tb_Netsuite_Account';

COMMIT TRANSACTION;
GO
DROP PROCEDURE #rebuild;
GO
