/*
    Staging tables for the NetSuite vendorBill object, generated by
    tools/generate_netsuite_tables.py from schemas/netsuite/vendorBill.xsd.
    Do not edit by hand: change the schema or the generator and regenerate.

    dbo.tb_Netsuite_VendorBill                   vendorBill
    dbo.tb_Netsuite_VendorBill_Item              vendorBill.item.items[]   (BPA_ParentID -> parent BPA_EntryID)
    dbo.tb_Netsuite_VendorBill_Expense           vendorBill.expense.items[]   (BPA_ParentID -> parent BPA_EntryID)

    Left out of tb_Netsuite_VendorBill: 253 custom fields, accountingBookDetail
    Left out of tb_Netsuite_VendorBill_Item: 86 custom fields
    Left out of tb_Netsuite_VendorBill_Expense: 86 custom fields

    Existing tables are renamed to <table>_bak (constraints included) before the
    new ones are created; drop the _bak tables once loading works. Stops without
    changes if a _bak table already exists. Runs in a single transaction.
*/
SET XACT_ABORT ON;
SET NOCOUNT ON;
IF OBJECT_ID(N'tempdb..#rebuild') IS NOT NULL DROP PROCEDURE #rebuild;
GO
-- Renames an existing table to <table>_bak (constraints get a _bak suffix too),
-- so the new definition can be created without losing data.
CREATE PROCEDURE #rebuild @table sysname AS
BEGIN
    DECLARE @bak sysname = @table + N'_bak', @old sysname, @new sysname, @obj nvarchar(300), @msg nvarchar(400);
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@table), N'U') IS NULL RETURN;
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@bak), N'U') IS NOT NULL
    BEGIN
        SET @msg = N'dbo.' + @bak + N' already exists; drop or rename it first.';
        THROW 50001, @msg, 1;
    END
    SET @obj = N'dbo.' + QUOTENAME(@table);
    EXEC sys.sp_rename @objname = @obj, @newname = @bak, @objtype = N'OBJECT';
    PRINT N'Renamed  dbo.' + @table + N' -> ' + @bak;
    DECLARE con CURSOR LOCAL FAST_FORWARD FOR
        SELECT name FROM sys.objects
        WHERE parent_object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@bak)) AND type IN ('PK', 'UQ', 'D', 'C', 'F');
    OPEN con;
    FETCH NEXT FROM con INTO @old;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @new = LEFT(@old, 124) + N'_bak';
        SET @obj = N'dbo.' + QUOTENAME(@old);
        EXEC sys.sp_rename @objname = @obj, @newname = @new, @objtype = N'OBJECT';
        FETCH NEXT FROM con INTO @old;
    END
    CLOSE con;
    DEALLOCATE con;
END
GO
BEGIN TRANSACTION;

EXEC #rebuild N'tb_Netsuite_VendorBill';
CREATE TABLE dbo.tb_Netsuite_VendorBill (
    BPA_Origin                 nvarchar(50)     NULL,
    BPA_Direction              nvarchar(50)     NULL,
    BPA_Company                nvarchar(50)     NULL,
    BPA_EntryID                uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_VendorBill_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID               uniqueidentifier NULL,
    BPA_Status                 int              NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Status DEFAULT ((0)),
    BPA_Reference              nvarchar(50)     NULL,
    BPA_Reference_Description  nvarchar(100)    NULL,
    BPA_Reference2             nvarchar(50)     NULL,
    BPA_Reference2_Description nvarchar(100)    NULL,
    BPA_Action                 nvarchar(1)      NULL,
    BPA_ReturnedID             nvarchar(50)     NULL,
    BPA_Syscreated             datetime         NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified            datetime         NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator             nvarchar(50)     NULL,
    BPA_Error                  nvarchar(max)    NULL,
    BPA_Error_Extended         nvarchar(max)    NULL,
    BPA_Description            nvarchar(255)    NULL,
    BPA_Failcount              int              NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid           uniqueidentifier NULL,
    BPA_TaskInstanceID         int              NULL,
    BPA_TaskID                 int              NULL,
    billAddr1                  nvarchar(255)    NULL,
    billAddr2                  nvarchar(255)    NULL,
    billAddr3                  nvarchar(255)    NULL,
    billAddress                nvarchar(4000)   NULL,
    billAddressee              nvarchar(255)    NULL,
    billAttention              nvarchar(255)    NULL,
    billCity                   nvarchar(255)    NULL,
    billingAddress_text        nvarchar(4000)   NULL,
    billOverride               nvarchar(4000)   NULL,
    billPhone                  nvarchar(255)    NULL,
    billState                  nvarchar(255)    NULL,
    billZip                    nvarchar(255)    NULL,
    createdDate                datetime2(3)     NULL,
    discountAmount             decimal(19,4)    NULL,
    discountDate               date             NULL,
    documentStatus             nvarchar(255)    NULL,
    dueDate                    date             NULL,
    endDate                    date             NULL,
    exchangeRate               decimal(28,10)   NULL,
    externalId                 nvarchar(255)    NULL,
    id                         nvarchar(100)    NOT NULL,
    lastModifiedDate           datetime2(3)     NULL,
    memo                       nvarchar(4000)   NULL,
    paymentHold                bit              NULL,
    prevDate                   date             NULL,
    received                   bit              NULL,
    refName                    nvarchar(255)    NULL,
    startDate                  date             NULL,
    tax2Total                  decimal(19,4)    NULL,
    taxTotal                   decimal(19,4)    NULL,
    toBePrinted                bit              NULL,
    total                      decimal(19,4)    NULL,
    tranDate                   date             NULL,
    tranId                     nvarchar(255)    NULL,
    transactionNumber          nvarchar(255)    NULL,
    userTotal                  decimal(19,4)    NULL,
    vatRegNum                  nvarchar(255)    NULL,
    entityId                   nvarchar(255)    NULL,
    entityRefName              nvarchar(255)    NULL,
    subsidiaryId               nvarchar(255)    NULL,
    subsidiaryRefName          nvarchar(255)    NULL,
    currencyId                 nvarchar(255)    NULL,
    currencyRefName            nvarchar(255)    NULL,
    accountId                  nvarchar(255)    NULL,
    accountRefName             nvarchar(255)    NULL,
    termsId                    nvarchar(255)    NULL,
    termsRefName               nvarchar(255)    NULL,
    approvalStatusId           nvarchar(255)    NULL,
    approvalStatusRefName      nvarchar(255)    NULL,
    departmentId               nvarchar(255)    NULL,
    departmentRefName          nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_VendorBill PRIMARY KEY CLUSTERED (BPA_EntryID)
);
PRINT N'Created  dbo.tb_Netsuite_VendorBill';

EXEC #rebuild N'tb_Netsuite_VendorBill_Item';
CREATE TABLE dbo.tb_Netsuite_VendorBill_Item (
    BPA_Origin                 nvarchar(50)     NULL,
    BPA_Direction              nvarchar(50)     NULL,
    BPA_Company                nvarchar(50)     NULL,
    BPA_EntryID                uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID               uniqueidentifier NULL,
    BPA_Status                 int              NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Status DEFAULT ((0)),
    BPA_Reference              nvarchar(50)     NULL,
    BPA_Reference_Description  nvarchar(100)    NULL,
    BPA_Reference2             nvarchar(50)     NULL,
    BPA_Reference2_Description nvarchar(100)    NULL,
    BPA_Action                 nvarchar(1)      NULL,
    BPA_ReturnedID             nvarchar(50)     NULL,
    BPA_Syscreated             datetime         NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified            datetime         NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator             nvarchar(50)     NULL,
    BPA_Error                  nvarchar(max)    NULL,
    BPA_Error_Extended         nvarchar(max)    NULL,
    BPA_Description            nvarchar(255)    NULL,
    BPA_Failcount              int              NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid           uniqueidentifier NULL,
    BPA_TaskInstanceID         int              NULL,
    BPA_TaskID                 int              NULL,
    amortizationEndDate        date             NULL,
    amortizationResidual       nvarchar(255)    NULL,
    amortizationType           nvarchar(255)    NULL,
    amortizStartDate           date             NULL,
    amount                     decimal(19,4)    NULL,
    baseGrossAmt               decimal(19,4)    NULL,
    deferRevRec                bit              NULL,
    description                nvarchar(4000)   NULL,
    grossAmt                   decimal(19,4)    NULL,
    initOqpBucket              nvarchar(255)    NULL,
    isBillable                 bit              NULL,
    isClosed                   bit              NULL,
    isOpen                     bit              NULL,
    isTaxable                  bit              NULL,
    isVsoeBundle               nvarchar(255)    NULL,
    line                       int              NULL,
    linked                     bit              NULL,
    marginal                   bit              NULL,
    options                    nvarchar(4000)   NULL,
    oqpBucket                  nvarchar(255)    NULL,
    orderLine                  int              NULL,
    printItems                 bit              NULL,
    quantity                   decimal(28,10)   NULL,
    rate                       decimal(28,10)   NULL,
    rateSchedule               nvarchar(255)    NULL,
    refName                    nvarchar(255)    NULL,
    scheduleType               nvarchar(255)    NULL,
    tax1Amt                    decimal(19,4)    NULL,
    taxRate1                   decimal(28,10)   NULL,
    taxRate2                   decimal(28,10)   NULL,
    uniqueKey                  int              NULL,
    units                      nvarchar(255)    NULL,
    vendorName                 nvarchar(255)    NULL,
    itemId                     nvarchar(255)    NULL,
    itemRefName                nvarchar(255)    NULL,
    taxCodeId                  nvarchar(255)    NULL,
    taxCodeRefName             nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_VendorBill_Item PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Item_ParentID ON dbo.tb_Netsuite_VendorBill_Item (BPA_ParentID);
PRINT N'Created  dbo.tb_Netsuite_VendorBill_Item';

EXEC #rebuild N'tb_Netsuite_VendorBill_Expense';
CREATE TABLE dbo.tb_Netsuite_VendorBill_Expense (
    BPA_Origin                 nvarchar(50)     NULL,
    BPA_Direction              nvarchar(50)     NULL,
    BPA_Company                nvarchar(50)     NULL,
    BPA_EntryID                uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID               uniqueidentifier NULL,
    BPA_Status                 int              NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Status DEFAULT ((0)),
    BPA_Reference              nvarchar(50)     NULL,
    BPA_Reference_Description  nvarchar(100)    NULL,
    BPA_Reference2             nvarchar(50)     NULL,
    BPA_Reference2_Description nvarchar(100)    NULL,
    BPA_Action                 nvarchar(1)      NULL,
    BPA_ReturnedID             nvarchar(50)     NULL,
    BPA_Syscreated             datetime         NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified            datetime         NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator             nvarchar(50)     NULL,
    BPA_Error                  nvarchar(max)    NULL,
    BPA_Error_Extended         nvarchar(max)    NULL,
    BPA_Description            nvarchar(255)    NULL,
    BPA_Failcount              int              NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid           uniqueidentifier NULL,
    BPA_TaskInstanceID         int              NULL,
    BPA_TaskID                 int              NULL,
    amortizationEndDate        date             NULL,
    amortizationResidual       nvarchar(255)    NULL,
    amortizationType           nvarchar(255)    NULL,
    amortizStartDate           date             NULL,
    amount                     decimal(19,4)    NULL,
    baseGrossAmt               decimal(19,4)    NULL,
    grossAmt                   decimal(19,4)    NULL,
    line                       int              NULL,
    memo                       nvarchar(4000)   NULL,
    orderDoc                   nvarchar(255)    NULL,
    orderLine                  nvarchar(255)    NULL,
    refName                    nvarchar(255)    NULL,
    scheduleType               nvarchar(255)    NULL,
    tax1Amt                    decimal(19,4)    NULL,
    taxRate1                   decimal(28,10)   NULL,
    taxRate2                   decimal(28,10)   NULL,
    accountId                  nvarchar(255)    NULL,
    accountRefName             nvarchar(255)    NULL,
    departmentId               nvarchar(255)    NULL,
    departmentRefName          nvarchar(255)    NULL,
    taxCodeId                  nvarchar(255)    NULL,
    taxCodeRefName             nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_VendorBill_Expense PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Expense_ParentID ON dbo.tb_Netsuite_VendorBill_Expense (BPA_ParentID);
PRINT N'Created  dbo.tb_Netsuite_VendorBill_Expense';

COMMIT TRANSACTION;
GO
DROP PROCEDURE #rebuild;
GO
