/*
    Staging tables for the NetSuite vendor object, generated by
    tools/generate_netsuite_tables.py from schemas/netsuite/vendor.xsd.
    Do not edit by hand: change the schema or the generator and regenerate.

    dbo.tb_Netsuite_Vendor                       vendor
    dbo.tb_Netsuite_Vendor_AddressBook           vendor.addressBook.items[]   (BPA_ParentID -> parent BPA_EntryID)

    Left out of tb_Netsuite_Vendor: 88 custom fields

    Existing tables are renamed to <table>_bak (constraints included) before the
    new ones are created; drop the _bak tables once loading works. Stops without
    changes if a _bak table already exists. Runs in a single transaction.
*/
SET XACT_ABORT ON;
SET NOCOUNT ON;
IF OBJECT_ID(N'tempdb..#rebuild') IS NOT NULL DROP PROCEDURE #rebuild;
GO
-- Renames an existing table to <table>_bak (constraints get a _bak suffix too),
-- so the new definition can be created without losing data.
CREATE PROCEDURE #rebuild @table sysname AS
BEGIN
    DECLARE @bak sysname = @table + N'_bak', @old sysname, @new sysname, @obj nvarchar(300), @msg nvarchar(400);
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@table), N'U') IS NULL RETURN;
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@bak), N'U') IS NOT NULL
    BEGIN
        SET @msg = N'dbo.' + @bak + N' already exists; drop or rename it first.';
        THROW 50001, @msg, 1;
    END
    SET @obj = N'dbo.' + QUOTENAME(@table);
    EXEC sys.sp_rename @objname = @obj, @newname = @bak, @objtype = N'OBJECT';
    PRINT N'Renamed  dbo.' + @table + N' -> ' + @bak;
    DECLARE con CURSOR LOCAL FAST_FORWARD FOR
        SELECT name FROM sys.objects
        WHERE parent_object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@bak)) AND type IN ('PK', 'UQ', 'D', 'C', 'F');
    OPEN con;
    FETCH NEXT FROM con INTO @old;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @new = LEFT(@old, 124) + N'_bak';
        SET @obj = N'dbo.' + QUOTENAME(@old);
        EXEC sys.sp_rename @objname = @obj, @newname = @new, @objtype = N'OBJECT';
        FETCH NEXT FROM con INTO @old;
    END
    CLOSE con;
    DEALLOCATE con;
END
GO
BEGIN TRANSACTION;

EXEC #rebuild N'tb_Netsuite_Vendor';
CREATE TABLE dbo.tb_Netsuite_Vendor (
    BPA_Origin                        nvarchar(50)     NULL,
    BPA_Direction                     nvarchar(50)     NULL,
    BPA_Company                       nvarchar(50)     NULL,
    BPA_EntryID                       uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_Vendor_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                      uniqueidentifier NULL,
    BPA_Status                        int              NULL CONSTRAINT DF_tb_Netsuite_Vendor_Status DEFAULT ((0)),
    BPA_Reference                     nvarchar(50)     NULL,
    BPA_Reference_Description         nvarchar(100)    NULL,
    BPA_Reference2                    nvarchar(50)     NULL,
    BPA_Reference2_Description        nvarchar(100)    NULL,
    BPA_Action                        nvarchar(1)      NULL,
    BPA_ReturnedID                    nvarchar(50)     NULL,
    BPA_Syscreated                    datetime         NULL CONSTRAINT DF_tb_Netsuite_Vendor_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified                   datetime         NULL CONSTRAINT DF_tb_Netsuite_Vendor_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator                    nvarchar(50)     NULL,
    BPA_Error                         nvarchar(max)    NULL,
    BPA_Error_Extended                nvarchar(max)    NULL,
    BPA_Description                   nvarchar(255)    NULL,
    BPA_Failcount                     int              NULL CONSTRAINT DF_tb_Netsuite_Vendor_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid                  uniqueidentifier NULL,
    BPA_TaskInstanceID                int              NULL,
    BPA_TaskID                        int              NULL,
    accountNumber                     nvarchar(255)    NULL,
    altEmail                          nvarchar(255)    NULL,
    altName                           nvarchar(255)    NULL,
    altPhone                          nvarchar(255)    NULL,
    autoName                          bit              NULL,
    balance                           decimal(19,4)    NULL,
    balancePrimary                    decimal(19,4)    NULL,
    bcn                               nvarchar(255)    NULL,
    comments                          nvarchar(4000)   NULL,
    companyName                       nvarchar(255)    NULL,
    creditLimit                       decimal(19,4)    NULL,
    dateCreated                       datetime2(3)     NULL,
    defaultAddress                    nvarchar(4000)   NULL,
    defaultShippingAddress            nvarchar(4000)   NULL,
    email                             nvarchar(255)    NULL,
    emailTransactions                 bit              NULL,
    entityId                          nvarchar(255)    NULL,
    externalId                        nvarchar(255)    NULL,
    fax                               nvarchar(255)    NULL,
    faxTransactions                   bit              NULL,
    firstName                         nvarchar(255)    NULL,
    homePhone                         nvarchar(255)    NULL,
    id                                nvarchar(100)    NOT NULL,
    is1099Eligible                    bit              NULL,
    isAutogeneratedRepresentingEntity bit              NULL,
    isInactive                        bit              NULL,
    isJobResourceVend                 bit              NULL,
    isPerson                          bit              NULL,
    lastModifiedDate                  datetime2(3)     NULL,
    lastName                          nvarchar(255)    NULL,
    legalName                         nvarchar(255)    NULL,
    middleName                        nvarchar(255)    NULL,
    mobilePhone                       nvarchar(255)    NULL,
    openingBalance                    decimal(19,4)    NULL,
    openingBalanceDate                date             NULL,
    phone                             nvarchar(255)    NULL,
    printOnCheckAs                    nvarchar(255)    NULL,
    printTransactions                 bit              NULL,
    refName                           nvarchar(255)    NULL,
    salutation                        nvarchar(255)    NULL,
    subsidiaryEdition                 nvarchar(255)    NULL,
    taxIdNum                          nvarchar(255)    NULL,
    title                             nvarchar(255)    NULL,
    url                               nvarchar(255)    NULL,
    vatRegNumber                      nvarchar(255)    NULL,
    currencyId                        nvarchar(255)    NULL,
    currencyRefName                   nvarchar(255)    NULL,
    subsidiaryId                      nvarchar(255)    NULL,
    subsidiaryRefName                 nvarchar(255)    NULL,
    termsId                           nvarchar(255)    NULL,
    termsRefName                      nvarchar(255)    NULL,
    categoryId                        nvarchar(255)    NULL,
    categoryRefName                   nvarchar(255)    NULL,
    defaultBankAccountId              nvarchar(255)    NULL,
    defaultBankAccountRefName         nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_Vendor PRIMARY KEY CLUSTERED (BPA_EntryID)
);
PRINT N'Created  dbo.tb_Netsuite_Vendor';

EXEC #rebuild N'tb_Netsuite_Vendor_AddressBook';
CREATE TABLE dbo.tb_Netsuite_Vendor_AddressBook (
    BPA_Origin                         nvarchar(50)     NULL,
    BPA_Direction                      nvarchar(50)     NULL,
    BPA_Company                        nvarchar(50)     NULL,
    BPA_EntryID                        uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_Vendor_AddressBook_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                       uniqueidentifier NULL,
    BPA_Status                         int              NULL CONSTRAINT DF_tb_Netsuite_Vendor_AddressBook_Status DEFAULT ((0)),
    BPA_Reference                      nvarchar(50)     NULL,
    BPA_Reference_Description          nvarchar(100)    NULL,
    BPA_Reference2                     nvarchar(50)     NULL,
    BPA_Reference2_Description         nvarchar(100)    NULL,
    BPA_Action                         nvarchar(1)      NULL,
    BPA_ReturnedID                     nvarchar(50)     NULL,
    BPA_Syscreated                     datetime         NULL CONSTRAINT DF_tb_Netsuite_Vendor_AddressBook_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified                    datetime         NULL CONSTRAINT DF_tb_Netsuite_Vendor_AddressBook_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator                     nvarchar(50)     NULL,
    BPA_Error                          nvarchar(max)    NULL,
    BPA_Error_Extended                 nvarchar(max)    NULL,
    BPA_Description                    nvarchar(255)    NULL,
    BPA_Failcount                      int              NULL CONSTRAINT DF_tb_Netsuite_Vendor_AddressBook_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid                   uniqueidentifier NULL,
    BPA_TaskInstanceID                 int              NULL,
    BPA_TaskID                         int              NULL,
    addressBookAddress_text            nvarchar(4000)   NULL,
    addressId                          nvarchar(255)    NULL,
    defaultBilling                     bit              NULL,
    defaultShipping                    bit              NULL,
    id                                 int              NULL,
    internalId                         int              NULL,
    label                              nvarchar(255)    NULL,
    lastModifiedDate                   datetime2(3)     NULL,
    refName                            nvarchar(255)    NULL,
    addressBookAddressAddr1            nvarchar(255)    NULL,
    addressBookAddressAddr2            nvarchar(255)    NULL,
    addressBookAddressAddr3            nvarchar(255)    NULL,
    addressBookAddressAddressee        nvarchar(255)    NULL,
    addressBookAddressAddrPhone        nvarchar(255)    NULL,
    addressBookAddressAddrText         nvarchar(255)    NULL,
    addressBookAddressAttention        nvarchar(255)    NULL,
    addressBookAddressCity             nvarchar(255)    NULL,
    addressBookAddressExternalId       nvarchar(255)    NULL,
    addressBookAddressLastModifiedDate datetime2(3)     NULL,
    addressBookAddressOverride         bit              NULL,
    addressBookAddressRefName          nvarchar(255)    NULL,
    addressBookAddressState            nvarchar(255)    NULL,
    addressBookAddressZip              nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_Vendor_AddressBook PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_Vendor_AddressBook_ParentID ON dbo.tb_Netsuite_Vendor_AddressBook (BPA_ParentID);
PRINT N'Created  dbo.tb_Netsuite_Vendor_AddressBook';

COMMIT TRANSACTION;
GO
DROP PROCEDURE #rebuild;
GO
