/*
    Staging tables for the NetSuite journalEntry object, generated by
    tools/generate_netsuite_tables.py from schemas/netsuite/journalEntry.xsd.
    Do not edit by hand: change the schema or the generator and regenerate.

    dbo.tb_Netsuite_JournalEntry                 journalEntry
    dbo.tb_Netsuite_JournalEntry_Line            journalEntry.line.items[]   (BPA_ParentID -> parent BPA_EntryID)

    Left out of tb_Netsuite_JournalEntry: 245 custom fields, accountingBookDetail
    Left out of tb_Netsuite_JournalEntry_Line: 81 custom fields

    Existing tables are renamed to <table>_bak (constraints included) before the
    new ones are created; drop the _bak tables once loading works. Stops without
    changes if a _bak table already exists. Runs in a single transaction.
*/
SET XACT_ABORT ON;
SET NOCOUNT ON;
IF OBJECT_ID(N'tempdb..#rebuild') IS NOT NULL DROP PROCEDURE #rebuild;
GO
-- Renames an existing table to <table>_bak (constraints get a _bak suffix too),
-- so the new definition can be created without losing data.
CREATE PROCEDURE #rebuild @table sysname AS
BEGIN
    DECLARE @bak sysname = @table + N'_bak', @old sysname, @new sysname, @obj nvarchar(300), @msg nvarchar(400);
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@table), N'U') IS NULL RETURN;
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@bak), N'U') IS NOT NULL
    BEGIN
        SET @msg = N'dbo.' + @bak + N' already exists; drop or rename it first.';
        THROW 50001, @msg, 1;
    END
    SET @obj = N'dbo.' + QUOTENAME(@table);
    EXEC sys.sp_rename @objname = @obj, @newname = @bak, @objtype = N'OBJECT';
    PRINT N'Renamed  dbo.' + @table + N' -> ' + @bak;
    DECLARE con CURSOR LOCAL FAST_FORWARD FOR
        SELECT name FROM sys.objects
        WHERE parent_object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@bak)) AND type IN ('PK', 'UQ', 'D', 'C', 'F');
    OPEN con;
    FETCH NEXT FROM con INTO @old;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @new = LEFT(@old, 124) + N'_bak';
        SET @obj = N'dbo.' + QUOTENAME(@old);
        EXEC sys.sp_rename @objname = @obj, @newname = @new, @objtype = N'OBJECT';
        FETCH NEXT FROM con INTO @old;
    END
    CLOSE con;
    DEALLOCATE con;
END
GO
BEGIN TRANSACTION;

EXEC #rebuild N'tb_Netsuite_JournalEntry';
CREATE TABLE dbo.tb_Netsuite_JournalEntry (
    BPA_Origin                 nvarchar(50)     NULL,
    BPA_Direction              nvarchar(50)     NULL,
    BPA_Company                nvarchar(50)     NULL,
    BPA_EntryID                uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_JournalEntry_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID               uniqueidentifier NULL,
    BPA_Status                 int              NULL CONSTRAINT DF_tb_Netsuite_JournalEntry_Status DEFAULT ((0)),
    BPA_Reference              nvarchar(50)     NULL,
    BPA_Reference_Description  nvarchar(100)    NULL,
    BPA_Reference2             nvarchar(50)     NULL,
    BPA_Reference2_Description nvarchar(100)    NULL,
    BPA_Action                 nvarchar(1)      NULL,
    BPA_ReturnedID             nvarchar(50)     NULL,
    BPA_Syscreated             datetime         NULL CONSTRAINT DF_tb_Netsuite_JournalEntry_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified            datetime         NULL CONSTRAINT DF_tb_Netsuite_JournalEntry_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator             nvarchar(50)     NULL,
    BPA_Error                  nvarchar(max)    NULL,
    BPA_Error_Extended         nvarchar(max)    NULL,
    BPA_Description            nvarchar(255)    NULL,
    BPA_Failcount              int              NULL CONSTRAINT DF_tb_Netsuite_JournalEntry_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid           uniqueidentifier NULL,
    BPA_TaskInstanceID         int              NULL,
    BPA_TaskID                 int              NULL,
    approved                   bit              NULL,
    createdDate                datetime2(3)     NULL,
    exchangeRate               decimal(28,10)   NULL,
    externalId                 nvarchar(255)    NULL,
    id                         nvarchar(100)    NOT NULL,
    isBookSpecific             bit              NULL,
    isReversal                 bit              NULL,
    lastModifiedDate           datetime2(3)     NULL,
    memo                       nvarchar(4000)   NULL,
    refName                    nvarchar(255)    NULL,
    reversalDate               date             NULL,
    reversalDefer              bit              NULL,
    reversalEntry              nvarchar(255)    NULL,
    tranDate                   date             NULL,
    tranId                     nvarchar(255)    NULL,
    transactionNumber          nvarchar(255)    NULL,
    void                       bit              NULL,
    currencyId                 nvarchar(255)    NULL,
    currencyRefName            nvarchar(255)    NULL,
    departmentId               nvarchar(255)    NULL,
    departmentRefName          nvarchar(255)    NULL,
    subsidiaryId               nvarchar(255)    NULL,
    subsidiaryRefName          nvarchar(255)    NULL,
    postingPeriodId            nvarchar(255)    NULL,
    postingPeriodRefName       nvarchar(255)    NULL,
    toSubsidiaryId             nvarchar(255)    NULL,
    toSubsidiaryRefName        nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_JournalEntry PRIMARY KEY CLUSTERED (BPA_EntryID)
);
PRINT N'Created  dbo.tb_Netsuite_JournalEntry';

EXEC #rebuild N'tb_Netsuite_JournalEntry_Line';
CREATE TABLE dbo.tb_Netsuite_JournalEntry_Line (
    BPA_Origin                 nvarchar(50)     NULL,
    BPA_Direction              nvarchar(50)     NULL,
    BPA_Company                nvarchar(50)     NULL,
    BPA_EntryID                uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_JournalEntry_Line_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID               uniqueidentifier NULL,
    BPA_Status                 int              NULL CONSTRAINT DF_tb_Netsuite_JournalEntry_Line_Status DEFAULT ((0)),
    BPA_Reference              nvarchar(50)     NULL,
    BPA_Reference_Description  nvarchar(100)    NULL,
    BPA_Reference2             nvarchar(50)     NULL,
    BPA_Reference2_Description nvarchar(100)    NULL,
    BPA_Action                 nvarchar(1)      NULL,
    BPA_ReturnedID             nvarchar(50)     NULL,
    BPA_Syscreated             datetime         NULL CONSTRAINT DF_tb_Netsuite_JournalEntry_Line_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified            datetime         NULL CONSTRAINT DF_tb_Netsuite_JournalEntry_Line_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator             nvarchar(50)     NULL,
    BPA_Error                  nvarchar(max)    NULL,
    BPA_Error_Extended         nvarchar(max)    NULL,
    BPA_Description            nvarchar(255)    NULL,
    BPA_Failcount              int              NULL CONSTRAINT DF_tb_Netsuite_JournalEntry_Line_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid           uniqueidentifier NULL,
    BPA_TaskInstanceID         int              NULL,
    BPA_TaskID                 int              NULL,
    amortizationType           nvarchar(255)    NULL,
    baseGrossAmt               decimal(19,4)    NULL,
    cleared                    bit              NULL,
    clearedDate                date             NULL,
    credit                     decimal(19,4)    NULL,
    debit                      decimal(19,4)    NULL,
    eliminate                  bit              NULL,
    endDate                    date             NULL,
    grossAmt                   decimal(19,4)    NULL,
    line                       int              NULL,
    lineCreatedDate            datetime2(3)     NULL,
    lineLastModifiedDate       datetime2(3)     NULL,
    memo                       nvarchar(4000)   NULL,
    refName                    nvarchar(255)    NULL,
    residual                   decimal(19,4)    NULL,
    startDate                  date             NULL,
    tax1Amt                    decimal(19,4)    NULL,
    taxRate1                   decimal(28,10)   NULL,
    accountId                  nvarchar(255)    NULL,
    accountRefName             nvarchar(255)    NULL,
    departmentId               nvarchar(255)    NULL,
    departmentRefName          nvarchar(255)    NULL,
    entityId                   nvarchar(255)    NULL,
    entityRefName              nvarchar(255)    NULL,
    classId                    nvarchar(255)    NULL,
    classRefName               nvarchar(255)    NULL,
    itemId                     nvarchar(255)    NULL,
    itemRefName                nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_JournalEntry_Line PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_JournalEntry_Line_ParentID ON dbo.tb_Netsuite_JournalEntry_Line (BPA_ParentID);
PRINT N'Created  dbo.tb_Netsuite_JournalEntry_Line';

COMMIT TRANSACTION;
GO
DROP PROCEDURE #rebuild;
GO
