/*
    Staging tables for the NetSuite customrecord_2663_entity_bank_details object, generated by
    tools/generate_netsuite_tables.py from schemas/netsuite/customrecord_2663_entity_bank_details.xsd.
    Do not edit by hand: change the schema or the generator and regenerate.

    dbo.tb_Netsuite_EntityBankDetails            customrecord_2663_entity_bank_details


    Existing tables are renamed to <table>_bak (constraints included) before the
    new ones are created; drop the _bak tables once loading works. Stops without
    changes if a _bak table already exists. Runs in a single transaction.
*/
SET XACT_ABORT ON;
SET NOCOUNT ON;
IF OBJECT_ID(N'tempdb..#rebuild') IS NOT NULL DROP PROCEDURE #rebuild;
GO
-- Renames an existing table to <table>_bak (constraints get a _bak suffix too),
-- so the new definition can be created without losing data.
CREATE PROCEDURE #rebuild @table sysname AS
BEGIN
    DECLARE @bak sysname = @table + N'_bak', @old sysname, @new sysname, @obj nvarchar(300), @msg nvarchar(400);
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@table), N'U') IS NULL RETURN;
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@bak), N'U') IS NOT NULL
    BEGIN
        SET @msg = N'dbo.' + @bak + N' already exists; drop or rename it first.';
        THROW 50001, @msg, 1;
    END
    SET @obj = N'dbo.' + QUOTENAME(@table);
    EXEC sys.sp_rename @objname = @obj, @newname = @bak, @objtype = N'OBJECT';
    PRINT N'Renamed  dbo.' + @table + N' -> ' + @bak;
    DECLARE con CURSOR LOCAL FAST_FORWARD FOR
        SELECT name FROM sys.objects
        WHERE parent_object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@bak)) AND type IN ('PK', 'UQ', 'D', 'C', 'F');
    OPEN con;
    FETCH NEXT FROM con INTO @old;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @new = LEFT(@old, 124) + N'_bak';
        SET @obj = N'dbo.' + QUOTENAME(@old);
        EXEC sys.sp_rename @objname = @obj, @newname = @new, @objtype = N'OBJECT';
        FETCH NEXT FROM con INTO @old;
    END
    CLOSE con;
    DEALLOCATE con;
END
GO
BEGIN TRANSACTION;

EXEC #rebuild N'tb_Netsuite_EntityBankDetails';
CREATE TABLE dbo.tb_Netsuite_EntityBankDetails (
    BPA_Origin                             nvarchar(50)     NULL,
    BPA_Direction                          nvarchar(50)     NULL,
    BPA_Company                            nvarchar(50)     NULL,
    BPA_EntryID                            uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_EntityBankDetails_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                           uniqueidentifier NULL,
    BPA_Status                             int              NULL CONSTRAINT DF_tb_Netsuite_EntityBankDetails_Status DEFAULT ((0)),
    BPA_Reference                          nvarchar(50)     NULL,
    BPA_Reference_Description              nvarchar(100)    NULL,
    BPA_Reference2                         nvarchar(50)     NULL,
    BPA_Reference2_Description             nvarchar(100)    NULL,
    BPA_Action                             nvarchar(1)      NULL,
    BPA_ReturnedID                         nvarchar(50)     NULL,
    BPA_Syscreated                         datetime         NULL CONSTRAINT DF_tb_Netsuite_EntityBankDetails_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified                        datetime         NULL CONSTRAINT DF_tb_Netsuite_EntityBankDetails_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator                         nvarchar(50)     NULL,
    BPA_Error                              nvarchar(max)    NULL,
    BPA_Error_Extended                     nvarchar(max)    NULL,
    BPA_Description                        nvarchar(255)    NULL,
    BPA_Failcount                          int              NULL CONSTRAINT DF_tb_Netsuite_EntityBankDetails_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid                       uniqueidentifier NULL,
    BPA_TaskInstanceID                     int              NULL,
    BPA_TaskID                             int              NULL,
    abbreviation                           nvarchar(255)    NULL,
    created                                datetime2(3)     NULL,
    custrecord_15152_is_acc_num_encrypted  bit              NULL,
    custrecord_2663_baby_bonus             bit              NULL,
    custrecord_2663_child_id               nvarchar(255)    NULL,
    custrecord_2663_customer_code          nvarchar(255)    NULL,
    custrecord_2663_date_ref_mandate       nvarchar(255)    NULL,
    custrecord_2663_edi                    bit              NULL,
    custrecord_2663_edi_value              nvarchar(255)    NULL,
    custrecord_2663_entity_acct_name       nvarchar(255)    NULL,
    custrecord_2663_entity_acct_no         nvarchar(255)    NULL,
    custrecord_2663_entity_acct_suffix     nvarchar(255)    NULL,
    custrecord_2663_entity_address1        nvarchar(255)    NULL,
    custrecord_2663_entity_address2        nvarchar(255)    NULL,
    custrecord_2663_entity_address3        nvarchar(255)    NULL,
    custrecord_2663_entity_bank_code       nvarchar(255)    NULL,
    custrecord_2663_entity_bank_name       nvarchar(255)    NULL,
    custrecord_2663_entity_bank_no         nvarchar(255)    NULL,
    custrecord_2663_entity_bban            nvarchar(255)    NULL,
    custrecord_2663_entity_bic             nvarchar(255)    NULL,
    custrecord_2663_entity_branch_name     nvarchar(255)    NULL,
    custrecord_2663_entity_branch_no       nvarchar(255)    NULL,
    custrecord_2663_entity_city            nvarchar(255)    NULL,
    custrecord_2663_entity_company_id      nvarchar(255)    NULL,
    custrecord_2663_entity_country_check   nvarchar(255)    NULL,
    custrecord_2663_entity_country_code    nvarchar(255)    NULL,
    custrecord_2663_entity_iban            nvarchar(255)    NULL,
    custrecord_2663_entity_iban_check      nvarchar(255)    NULL,
    custrecord_2663_entity_issuer_num      nvarchar(255)    NULL,
    custrecord_2663_entity_payment_desc    nvarchar(255)    NULL,
    custrecord_2663_entity_processor_code  nvarchar(255)    NULL,
    custrecord_2663_entity_signature       nvarchar(255)    NULL,
    custrecord_2663_entity_state           nvarchar(255)    NULL,
    custrecord_2663_entity_swift           nvarchar(255)    NULL,
    custrecord_2663_entity_zip             nvarchar(255)    NULL,
    custrecord_2663_final_pay_date         nvarchar(255)    NULL,
    custrecord_2663_first_pay_date         nvarchar(255)    NULL,
    custrecord_2663_num_payments           int              NULL,
    custrecord_2663_reference              nvarchar(255)    NULL,
    externalId                             nvarchar(255)    NULL,
    id                                     nvarchar(100)    NOT NULL,
    isInactive                             bit              NULL,
    lastmodified                           datetime2(3)     NULL,
    name                                   nvarchar(255)    NULL,
    recordId                               int              NULL,
    refName                                nvarchar(255)    NULL,
    scriptId                               nvarchar(255)    NULL,
    custrecord_2663_parent_vendorId        nvarchar(255)    NULL,
    custrecord_2663_parent_vendorRefName   nvarchar(255)    NULL,
    custrecord_2663_parent_customerId      nvarchar(255)    NULL,
    custrecord_2663_parent_customerRefName nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_EntityBankDetails PRIMARY KEY CLUSTERED (BPA_EntryID)
);
PRINT N'Created  dbo.tb_Netsuite_EntityBankDetails';

COMMIT TRANSACTION;
GO
DROP PROCEDURE #rebuild;
GO
