/*
    Staging tables for the NetSuite customerPayment object, generated by
    tools/generate_netsuite_tables.py from schemas/netsuite/customerPayment.xsd.
    Do not edit by hand: change the schema or the generator and regenerate.

    dbo.tb_Netsuite_CustomerPayment              customerPayment
    dbo.tb_Netsuite_CustomerPayment_Apply        customerPayment.apply.items[]   (BPA_ParentID -> parent BPA_EntryID)

    Left out of tb_Netsuite_CustomerPayment: 60 custom fields

    Existing tables are renamed to <table>_bak (constraints included) before the
    new ones are created; drop the _bak tables once loading works. Stops without
    changes if a _bak table already exists. Runs in a single transaction.
*/
SET XACT_ABORT ON;
SET NOCOUNT ON;
IF OBJECT_ID(N'tempdb..#rebuild') IS NOT NULL DROP PROCEDURE #rebuild;
GO
-- Renames an existing table to <table>_bak (constraints get a _bak suffix too),
-- so the new definition can be created without losing data.
CREATE PROCEDURE #rebuild @table sysname AS
BEGIN
    DECLARE @bak sysname = @table + N'_bak', @old sysname, @new sysname, @obj nvarchar(300), @msg nvarchar(400);
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@table), N'U') IS NULL RETURN;
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@bak), N'U') IS NOT NULL
    BEGIN
        SET @msg = N'dbo.' + @bak + N' already exists; drop or rename it first.';
        THROW 50001, @msg, 1;
    END
    SET @obj = N'dbo.' + QUOTENAME(@table);
    EXEC sys.sp_rename @objname = @obj, @newname = @bak, @objtype = N'OBJECT';
    PRINT N'Renamed  dbo.' + @table + N' -> ' + @bak;
    DECLARE con CURSOR LOCAL FAST_FORWARD FOR
        SELECT name FROM sys.objects
        WHERE parent_object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@bak)) AND type IN ('PK', 'UQ', 'D', 'C', 'F');
    OPEN con;
    FETCH NEXT FROM con INTO @old;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @new = LEFT(@old, 124) + N'_bak';
        SET @obj = N'dbo.' + QUOTENAME(@old);
        EXEC sys.sp_rename @objname = @obj, @newname = @new, @objtype = N'OBJECT';
        FETCH NEXT FROM con INTO @old;
    END
    CLOSE con;
    DEALLOCATE con;
END
GO
BEGIN TRANSACTION;

EXEC #rebuild N'tb_Netsuite_CustomerPayment';
CREATE TABLE dbo.tb_Netsuite_CustomerPayment (
    BPA_Origin                 nvarchar(50)     NULL,
    BPA_Direction              nvarchar(50)     NULL,
    BPA_Company                nvarchar(50)     NULL,
    BPA_EntryID                uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_CustomerPayment_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID               uniqueidentifier NULL,
    BPA_Status                 int              NULL CONSTRAINT DF_tb_Netsuite_CustomerPayment_Status DEFAULT ((0)),
    BPA_Reference              nvarchar(50)     NULL,
    BPA_Reference_Description  nvarchar(100)    NULL,
    BPA_Reference2             nvarchar(50)     NULL,
    BPA_Reference2_Description nvarchar(100)    NULL,
    BPA_Action                 nvarchar(1)      NULL,
    BPA_ReturnedID             nvarchar(50)     NULL,
    BPA_Syscreated             datetime         NULL CONSTRAINT DF_tb_Netsuite_CustomerPayment_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified            datetime         NULL CONSTRAINT DF_tb_Netsuite_CustomerPayment_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator             nvarchar(50)     NULL,
    BPA_Error                  nvarchar(max)    NULL,
    BPA_Error_Extended         nvarchar(max)    NULL,
    BPA_Description            nvarchar(255)    NULL,
    BPA_Failcount              int              NULL CONSTRAINT DF_tb_Netsuite_CustomerPayment_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid           uniqueidentifier NULL,
    BPA_TaskInstanceID         int              NULL,
    BPA_TaskID                 int              NULL,
    applied                    decimal(19,4)    NULL,
    balance                    decimal(19,4)    NULL,
    cardSwipe                  nvarchar(255)    NULL,
    checkNumber                nvarchar(255)    NULL,
    cleared                    bit              NULL,
    clearedDate                date             NULL,
    consolidateBalance         decimal(19,4)    NULL,
    createdDate                datetime2(3)     NULL,
    debitKsn                   nvarchar(255)    NULL,
    debitPinBlock              nvarchar(255)    NULL,
    dynamicDescriptor          nvarchar(255)    NULL,
    exchangeRate               decimal(28,10)   NULL,
    excludeFromGLNumbering     bit              NULL,
    externalId                 nvarchar(255)    NULL,
    id                         nvarchar(100)    NOT NULL,
    inputPnRefNum              nvarchar(255)    NULL,
    inputReferenceCode         nvarchar(255)    NULL,
    integrationId              nvarchar(255)    NULL,
    lastModifiedDate           datetime2(3)     NULL,
    memo                       nvarchar(4000)   NULL,
    originator                 nvarchar(255)    NULL,
    outputAuthCode             nvarchar(255)    NULL,
    outputReferenceCode        nvarchar(255)    NULL,
    payment                    decimal(19,4)    NULL,
    paymentCardCsc             nvarchar(255)    NULL,
    paymentDeviceId            nvarchar(255)    NULL,
    paymentInstrumentLimit     decimal(19,4)    NULL,
    pending                    decimal(19,4)    NULL,
    prevDate                   date             NULL,
    refName                    nvarchar(255)    NULL,
    toBeEmailed                bit              NULL,
    total                      decimal(19,4)    NULL,
    tranDate                   date             NULL,
    tranId                     nvarchar(255)    NULL,
    unapplied                  decimal(19,4)    NULL,
    accountId                  nvarchar(255)    NULL,
    accountRefName             nvarchar(255)    NULL,
    currencyId                 nvarchar(255)    NULL,
    currencyRefName            nvarchar(255)    NULL,
    customerId                 nvarchar(255)    NULL,
    customerRefName            nvarchar(255)    NULL,
    subsidiaryId               nvarchar(255)    NULL,
    subsidiaryRefName          nvarchar(255)    NULL,
    postingPeriodId            nvarchar(255)    NULL,
    postingPeriodRefName       nvarchar(255)    NULL,
    aracctId                   nvarchar(255)    NULL,
    aracctRefName              nvarchar(255)    NULL,
    undepFundsId               nvarchar(255)    NULL,
    undepFundsRefName          nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_CustomerPayment PRIMARY KEY CLUSTERED (BPA_EntryID)
);
PRINT N'Created  dbo.tb_Netsuite_CustomerPayment';

EXEC #rebuild N'tb_Netsuite_CustomerPayment_Apply';
CREATE TABLE dbo.tb_Netsuite_CustomerPayment_Apply (
    BPA_Origin                 nvarchar(50)     NULL,
    BPA_Direction              nvarchar(50)     NULL,
    BPA_Company                nvarchar(50)     NULL,
    BPA_EntryID                uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_CustomerPayment_Apply_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID               uniqueidentifier NULL,
    BPA_Status                 int              NULL CONSTRAINT DF_tb_Netsuite_CustomerPayment_Apply_Status DEFAULT ((0)),
    BPA_Reference              nvarchar(50)     NULL,
    BPA_Reference_Description  nvarchar(100)    NULL,
    BPA_Reference2             nvarchar(50)     NULL,
    BPA_Reference2_Description nvarchar(100)    NULL,
    BPA_Action                 nvarchar(1)      NULL,
    BPA_ReturnedID             nvarchar(50)     NULL,
    BPA_Syscreated             datetime         NULL CONSTRAINT DF_tb_Netsuite_CustomerPayment_Apply_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified            datetime         NULL CONSTRAINT DF_tb_Netsuite_CustomerPayment_Apply_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator             nvarchar(50)     NULL,
    BPA_Error                  nvarchar(max)    NULL,
    BPA_Error_Extended         nvarchar(max)    NULL,
    BPA_Description            nvarchar(255)    NULL,
    BPA_Failcount              int              NULL CONSTRAINT DF_tb_Netsuite_CustomerPayment_Apply_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid           uniqueidentifier NULL,
    BPA_TaskInstanceID         int              NULL,
    BPA_TaskID                 int              NULL,
    amount                     decimal(19,4)    NULL,
    apply                      bit              NULL,
    applyDate                  date             NULL,
    createdFrom                nvarchar(255)    NULL,
    currency                   nvarchar(255)    NULL,
    disc                       decimal(19,4)    NULL,
    discAmt                    decimal(19,4)    NULL,
    due                        decimal(19,4)    NULL,
    line                       int              NULL,
    refName                    nvarchar(255)    NULL,
    refNum                     nvarchar(255)    NULL,
    total                      decimal(19,4)    NULL,
    type                       nvarchar(255)    NULL,
    docId                      nvarchar(255)    NULL,
    docRefName                 nvarchar(255)    NULL,
    CONSTRAINT PK_tb_Netsuite_CustomerPayment_Apply PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_CustomerPayment_Apply_ParentID ON dbo.tb_Netsuite_CustomerPayment_Apply (BPA_ParentID);
PRINT N'Created  dbo.tb_Netsuite_CustomerPayment_Apply';

COMMIT TRANSACTION;
GO
DROP PROCEDURE #rebuild;
GO
