/*
    Foundation Group - bring the existing NetSuite vendor bill staging tables in line with
    the spec (tools/netsuite_masterdata.py). Safe to run more than once:

    1. Creates a child table that does not exist yet (full definition).
    2. Adds every column that is missing, as NULL (also the ones that are
       NOT NULL in the spec: existing rows have no value for them).
       Changes decimal columns that the spec stores as text to nvarchar(50)
       (numbers with a decimal comma; lossless). The vw_ views type them.
    3. Reports (PRINT), without changing anything: columns whose type differs
       from the spec, columns that should be NOT NULL, and columns that are not
       in the spec. Change those by hand after checking the data.

    Tables:
        dbo.tb_Netsuite_VendorBill
        dbo.tb_Netsuite_VendorBill_Expense
        dbo.tb_Netsuite_VendorBill_Item

    The header table must exist (run the CREATE script for a new database).
    Runs in a single transaction. Generated by
    tools/netsuite_masterdata.py sql alter --group vendorbill; do not edit by hand.
*/
SET XACT_ABORT ON;
SET NOCOUNT ON;
GO
BEGIN TRANSACTION;

IF OBJECT_ID(N'dbo.tb_Netsuite_VendorBill', N'U') IS NULL
    THROW 50101, N'dbo.tb_Netsuite_VendorBill does not exist: run the CREATE script first.', 1;

-- vendorBill/expense/items -> dbo.tb_Netsuite_VendorBill_Expense: one row per line
IF OBJECT_ID(N'dbo.tb_Netsuite_VendorBill_Expense', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.tb_Netsuite_VendorBill_Expense (
        -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
        BPA_Origin                  nvarchar(50) NULL,
        BPA_Direction               nvarchar(50) NULL,
        BPA_Company                 nvarchar(50) NULL,
        BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_EntryID DEFAULT (newsequentialid()),
        BPA_ParentID                uniqueidentifier NULL,
        BPA_Status                  int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Status DEFAULT ((0)),
        BPA_Reference               nvarchar(50) NULL,
        BPA_Reference_Description   nvarchar(100) NULL,
        BPA_Reference2              nvarchar(50) NULL,
        BPA_Reference2_Description  nvarchar(100) NULL,
        BPA_Action                  nvarchar(1) NULL,
        BPA_ReturnedID              nvarchar(50) NULL,
        BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Syscreated DEFAULT (getdate()),
        BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Sysmodified DEFAULT (getdate()),
        BPA_Syscreator              nvarchar(50) NULL,
        BPA_Error                   nvarchar(max) NULL,
        BPA_Error_Extended          nvarchar(max) NULL,
        BPA_Description             nvarchar(255) NULL,
        BPA_Failcount               int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Failcount DEFAULT ((0)),
        BPA_Orig_Entryid            uniqueidentifier NULL,
        BPA_TaskInstanceID          int NULL,
        BPA_TaskID                  int NULL,

        -- Parent: BPA_ParentID = tb_Netsuite_VendorBill.BPA_EntryID
        vendorBillId                nvarchar(100) NOT NULL,     -- vendorBill/id (the parent's NetSuite id)

        -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
        line                        int NOT NULL,
        accountId                   nvarchar(100) NULL,
        accountRefName              nvarchar(400) NULL,
        amount                      nvarchar(50) NULL,          -- net; number as text, decimal(19,4) in the view
        taxCodeId                   nvarchar(100) NULL,
        taxCodeRefName              nvarchar(100) NULL,
        taxRate1                    nvarchar(50) NULL,          -- 1.0% -> 1.0000; number as text, decimal(9,4) in the view
        tax1Amt                     nvarchar(50) NULL,          -- number as text, decimal(19,4) in the view
        grossAmt                    nvarchar(50) NULL,          -- number as text, decimal(19,4) in the view
        memo                        nvarchar(4000) NULL,
        departmentId                nvarchar(100) NULL,
        departmentRefName           nvarchar(400) NULL,
        classId                     nvarchar(100) NULL,
        classRefName                nvarchar(400) NULL,
        locationId                  nvarchar(100) NULL,
        locationRefName             nvarchar(400) NULL,
        customerId                  nvarchar(100) NULL,
        customerRefName             nvarchar(400) NULL,
        isBillable                  bit NULL,
        categoryId                  nvarchar(100) NULL,
        categoryRefName             nvarchar(400) NULL,
        amortizationSchedId         nvarchar(100) NULL,
        amortizationSchedRefName    nvarchar(400) NULL,
        amortizStartDate            date NULL,
        amortizationEndDate         date NULL,
        amortizationResidual        nvarchar(100) NULL,
        amortizationType            nvarchar(50) NULL,          -- STANDARD, VARIABLE
        scheduleType                nvarchar(50) NULL,          -- Amortization
        orderDoc                    nvarchar(100) NULL,         -- linked purchase order
        orderLine                   nvarchar(50) NULL,
        CONSTRAINT PK_tb_Netsuite_VendorBill_Expense PRIMARY KEY CLUSTERED (BPA_EntryID)
    );
    CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Expense_BPA_ParentID ON dbo.tb_Netsuite_VendorBill_Expense (BPA_ParentID);
    CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Expense_vendorBillId ON dbo.tb_Netsuite_VendorBill_Expense (vendorBillId, line);
    PRINT N'Created  dbo.tb_Netsuite_VendorBill_Expense';
END
ELSE
    PRINT N'Skipped  dbo.tb_Netsuite_VendorBill_Expense (already exists)';

-- vendorBill/item/items -> dbo.tb_Netsuite_VendorBill_Item: one row per line
IF OBJECT_ID(N'dbo.tb_Netsuite_VendorBill_Item', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.tb_Netsuite_VendorBill_Item (
        -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
        BPA_Origin                  nvarchar(50) NULL,
        BPA_Direction               nvarchar(50) NULL,
        BPA_Company                 nvarchar(50) NULL,
        BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_EntryID DEFAULT (newsequentialid()),
        BPA_ParentID                uniqueidentifier NULL,
        BPA_Status                  int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Status DEFAULT ((0)),
        BPA_Reference               nvarchar(50) NULL,
        BPA_Reference_Description   nvarchar(100) NULL,
        BPA_Reference2              nvarchar(50) NULL,
        BPA_Reference2_Description  nvarchar(100) NULL,
        BPA_Action                  nvarchar(1) NULL,
        BPA_ReturnedID              nvarchar(50) NULL,
        BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Syscreated DEFAULT (getdate()),
        BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Sysmodified DEFAULT (getdate()),
        BPA_Syscreator              nvarchar(50) NULL,
        BPA_Error                   nvarchar(max) NULL,
        BPA_Error_Extended          nvarchar(max) NULL,
        BPA_Description             nvarchar(255) NULL,
        BPA_Failcount               int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Failcount DEFAULT ((0)),
        BPA_Orig_Entryid            uniqueidentifier NULL,
        BPA_TaskInstanceID          int NULL,
        BPA_TaskID                  int NULL,

        -- Parent: BPA_ParentID = tb_Netsuite_VendorBill.BPA_EntryID
        vendorBillId                nvarchar(100) NOT NULL,     -- vendorBill/id (the parent's NetSuite id)

        -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
        line                        int NOT NULL,
        uniqueKey                   int NULL,                   -- line unique key
        itemId                      nvarchar(100) NULL,
        itemRefName                 nvarchar(400) NULL,
        vendorName                  nvarchar(255) NULL,         -- vendor's item code
        description                 nvarchar(4000) NULL,
        quantity                    nvarchar(50) NULL,          -- number as text, decimal(28,10) in the view
        units                       nvarchar(100) NULL,
        rate                        nvarchar(50) NULL,          -- number as text, decimal(28,10) in the view
        amount                      nvarchar(50) NULL,          -- net; number as text, decimal(19,4) in the view
        taxCodeId                   nvarchar(100) NULL,
        taxCodeRefName              nvarchar(100) NULL,
        taxRate1                    nvarchar(50) NULL,          -- number as text, decimal(9,4) in the view
        tax1Amt                     nvarchar(50) NULL,          -- number as text, decimal(19,4) in the view
        grossAmt                    nvarchar(50) NULL,          -- number as text, decimal(19,4) in the view
        departmentId                nvarchar(100) NULL,
        departmentRefName           nvarchar(400) NULL,
        classId                     nvarchar(100) NULL,
        classRefName                nvarchar(400) NULL,
        customerId                  nvarchar(100) NULL,
        customerRefName             nvarchar(400) NULL,
        isBillable                  bit NULL,
        orderLine                   int NULL,                   -- linked purchase order line
        amortizStartDate            date NULL,
        amortizationEndDate         date NULL,
        amortizationResidual        nvarchar(100) NULL,
        CONSTRAINT PK_tb_Netsuite_VendorBill_Item PRIMARY KEY CLUSTERED (BPA_EntryID)
    );
    CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Item_BPA_ParentID ON dbo.tb_Netsuite_VendorBill_Item (BPA_ParentID);
    CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Item_vendorBillId ON dbo.tb_Netsuite_VendorBill_Item (vendorBillId, line);
    PRINT N'Created  dbo.tb_Netsuite_VendorBill_Item';
END
ELSE
    PRINT N'Skipped  dbo.tb_Netsuite_VendorBill_Item (already exists)';

-- the spec: every column with its type
DECLARE @spec TABLE (tbl sysname, col sysname, typ nvarchar(100), not_null bit, df_name sysname NULL, df nvarchar(100) NULL, ord int IDENTITY);
INSERT INTO @spec (tbl, col, typ, not_null, df_name, df) VALUES
    (N'tb_Netsuite_VendorBill', N'BPA_Origin', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_Direction', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_Company', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_EntryID', N'uniqueidentifier', 1, N'DF_tb_Netsuite_VendorBill_EntryID', N'(newsequentialid())'),
    (N'tb_Netsuite_VendorBill', N'BPA_ParentID', N'uniqueidentifier', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_Status', N'int', 0, N'DF_tb_Netsuite_VendorBill_Status', N'((0))'),
    (N'tb_Netsuite_VendorBill', N'BPA_Reference', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_Reference_Description', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_Reference2', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_Reference2_Description', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_Action', N'nvarchar(1)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_ReturnedID', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_Syscreated', N'datetime', 0, N'DF_tb_Netsuite_VendorBill_Syscreated', N'(getdate())'),
    (N'tb_Netsuite_VendorBill', N'BPA_Sysmodified', N'datetime', 0, N'DF_tb_Netsuite_VendorBill_Sysmodified', N'(getdate())'),
    (N'tb_Netsuite_VendorBill', N'BPA_Syscreator', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_Error', N'nvarchar(max)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_Error_Extended', N'nvarchar(max)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_Description', N'nvarchar(255)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_Failcount', N'int', 0, N'DF_tb_Netsuite_VendorBill_Failcount', N'((0))'),
    (N'tb_Netsuite_VendorBill', N'BPA_Orig_Entryid', N'uniqueidentifier', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_TaskInstanceID', N'int', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'BPA_TaskID', N'int', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'id', N'nvarchar(100)', 1, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'externalId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'tranId', N'nvarchar(255)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'transactionNumber', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'tranDate', N'date', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'dueDate', N'date', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'createdDate', N'datetime2(0)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'lastModifiedDate', N'datetime2(0)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'entityId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'entityRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'subsidiaryId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'subsidiaryRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'currencyId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'currencyRefName', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'accountId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'accountRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'postingPeriodId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'postingPeriodRefName', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'termsId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'termsRefName', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'approvalStatusId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'approvalStatusRefName', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'statusId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'statusRefName', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'departmentId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'departmentRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'classId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'classRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'locationId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'locationRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'exchangeRate', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'total', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'userTotal', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'taxTotal', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'discountAmount', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'discountDate', N'date', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'memo', N'nvarchar(4000)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'documentStatus', N'nvarchar(10)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'paymentHold', N'bit', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'received', N'bit', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'toBePrinted', N'bit', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'vatRegNum', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'billAddressee', N'nvarchar(255)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'billAttention', N'nvarchar(255)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'billAddr1', N'nvarchar(255)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'billAddr2', N'nvarchar(255)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'billAddr3', N'nvarchar(255)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'billCity', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'billState', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'billZip', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'billCountryId', N'nvarchar(10)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'billCountryRefName', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'billAddress', N'nvarchar(1000)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'cseg_bit_4weeksId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'cseg_bit_4weeksRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_document_date', N'date', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_establishment_code', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_15529_vendor_entity_bankId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_15529_vendor_entity_bankRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_11187_pref_entity_bankId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_11187_pref_entity_bankRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_9997_is_for_ep_eft', N'bit', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_11724_pay_bank_fees', N'bit', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_stc_amount_after_discount', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_stc_tax_after_discount', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_stc_total_after_discount', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_stc_discountpercent', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_stc_daysuntilexpiry', N'int', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_stc_payment_transaction_id', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill', N'custbody_bit_zonalurl', N'nvarchar(1000)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Origin', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Direction', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Company', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_EntryID', N'uniqueidentifier', 1, N'DF_tb_Netsuite_VendorBill_Expense_EntryID', N'(newsequentialid())'),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_ParentID', N'uniqueidentifier', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Status', N'int', 0, N'DF_tb_Netsuite_VendorBill_Expense_Status', N'((0))'),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Reference', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Reference_Description', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Reference2', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Reference2_Description', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Action', N'nvarchar(1)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_ReturnedID', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Syscreated', N'datetime', 0, N'DF_tb_Netsuite_VendorBill_Expense_Syscreated', N'(getdate())'),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Sysmodified', N'datetime', 0, N'DF_tb_Netsuite_VendorBill_Expense_Sysmodified', N'(getdate())'),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Syscreator', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Error', N'nvarchar(max)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Error_Extended', N'nvarchar(max)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Description', N'nvarchar(255)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Failcount', N'int', 0, N'DF_tb_Netsuite_VendorBill_Expense_Failcount', N'((0))'),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_Orig_Entryid', N'uniqueidentifier', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_TaskInstanceID', N'int', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'BPA_TaskID', N'int', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'vendorBillId', N'nvarchar(100)', 1, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'line', N'int', 1, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'accountId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'accountRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'amount', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'taxCodeId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'taxCodeRefName', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'taxRate1', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'tax1Amt', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'grossAmt', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'memo', N'nvarchar(4000)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'departmentId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'departmentRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'classId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'classRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'locationId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'locationRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'customerId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'customerRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'isBillable', N'bit', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'categoryId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'categoryRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'amortizationSchedId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'amortizationSchedRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'amortizStartDate', N'date', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'amortizationEndDate', N'date', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'amortizationResidual', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'amortizationType', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'scheduleType', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'orderDoc', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Expense', N'orderLine', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Origin', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Direction', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Company', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_EntryID', N'uniqueidentifier', 1, N'DF_tb_Netsuite_VendorBill_Item_EntryID', N'(newsequentialid())'),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_ParentID', N'uniqueidentifier', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Status', N'int', 0, N'DF_tb_Netsuite_VendorBill_Item_Status', N'((0))'),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Reference', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Reference_Description', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Reference2', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Reference2_Description', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Action', N'nvarchar(1)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_ReturnedID', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Syscreated', N'datetime', 0, N'DF_tb_Netsuite_VendorBill_Item_Syscreated', N'(getdate())'),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Sysmodified', N'datetime', 0, N'DF_tb_Netsuite_VendorBill_Item_Sysmodified', N'(getdate())'),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Syscreator', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Error', N'nvarchar(max)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Error_Extended', N'nvarchar(max)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Description', N'nvarchar(255)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Failcount', N'int', 0, N'DF_tb_Netsuite_VendorBill_Item_Failcount', N'((0))'),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_Orig_Entryid', N'uniqueidentifier', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_TaskInstanceID', N'int', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'BPA_TaskID', N'int', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'vendorBillId', N'nvarchar(100)', 1, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'line', N'int', 1, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'uniqueKey', N'int', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'itemId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'itemRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'vendorName', N'nvarchar(255)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'description', N'nvarchar(4000)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'quantity', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'units', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'rate', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'amount', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'taxCodeId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'taxCodeRefName', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'taxRate1', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'tax1Amt', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'grossAmt', N'nvarchar(50)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'departmentId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'departmentRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'classId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'classRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'customerId', N'nvarchar(100)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'customerRefName', N'nvarchar(400)', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'isBillable', N'bit', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'orderLine', N'int', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'amortizStartDate', N'date', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'amortizationEndDate', N'date', 0, NULL, NULL),
    (N'tb_Netsuite_VendorBill_Item', N'amortizationResidual', N'nvarchar(100)', 0, NULL, NULL);

DECLARE @tbl sysname, @col sysname, @typ nvarchar(100), @nn bit, @dfn sysname, @df nvarchar(100),
        @sql nvarchar(max), @have nvarchar(100), @have_nn bit;

DECLARE c CURSOR LOCAL FAST_FORWARD FOR SELECT tbl, col, typ, not_null, df_name, df FROM @spec ORDER BY ord;
OPEN c;
FETCH NEXT FROM c INTO @tbl, @col, @typ, @nn, @dfn, @df;
WHILE @@FETCH_STATUS = 0
BEGIN
    SELECT @have = NULL, @have_nn = NULL;
    SELECT @have = CASE
               WHEN ty.name IN (N'nvarchar', N'nchar') THEN ty.name + N'(' + IIF(c.max_length = -1, N'max', CAST(c.max_length / 2 AS nvarchar(10))) + N')'
               WHEN ty.name IN (N'varchar', N'char') THEN ty.name + N'(' + IIF(c.max_length = -1, N'max', CAST(c.max_length AS nvarchar(10))) + N')'
               WHEN ty.name IN (N'decimal', N'numeric') THEN ty.name + N'(' + CAST(c.precision AS nvarchar(5)) + N',' + CAST(c.scale AS nvarchar(5)) + N')'
               WHEN ty.name IN (N'datetime2', N'datetimeoffset', N'time') THEN ty.name + N'(' + CAST(c.scale AS nvarchar(5)) + N')'
               ELSE ty.name END,
           @have_nn = IIF(c.is_nullable = 1, 0, 1)
    FROM sys.columns c
    JOIN sys.types ty ON ty.user_type_id = c.user_type_id
    WHERE c.object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@tbl)) AND c.name = @col;

    IF @have IS NULL
    BEGIN
        SET @sql = N'ALTER TABLE dbo.' + QUOTENAME(@tbl) + N' ADD ' + QUOTENAME(@col) + N' ' + @typ + N' NULL'
                 + ISNULL(N' CONSTRAINT ' + QUOTENAME(@dfn) + N' DEFAULT ' + @df, N'') + N';';
        EXEC sys.sp_executesql @sql;
        PRINT N'Added    ' + @tbl + N'.' + @col + N' ' + @typ;
    END
    ELSE
    BEGIN
        IF @have <> @typ AND @have LIKE N'decimal(%' AND @typ LIKE N'nvarchar(%'
        BEGIN
            -- number column -> text column (decimal comma from the connector): lossless
            SET @sql = N'ALTER TABLE dbo.' + QUOTENAME(@tbl) + N' ALTER COLUMN ' + QUOTENAME(@col) + N' ' + @typ
                     + IIF(@have_nn = 1, N' NOT NULL', N' NULL') + N';';
            EXEC sys.sp_executesql @sql;
            PRINT N'Changed  ' + @tbl + N'.' + @col + N' ' + @have + N' -> ' + @typ;
        END
        ELSE IF @have <> @typ
            PRINT N'TYPE     ' + @tbl + N'.' + @col + N' is ' + @have + N', spec ' + @typ + N' (not changed)';
        IF @nn = 1 AND @have_nn = 0
            PRINT N'NULL     ' + @tbl + N'.' + @col + N' allows NULL, spec NOT NULL (not changed)';
    END
    FETCH NEXT FROM c INTO @tbl, @col, @typ, @nn, @dfn, @df;
END
CLOSE c;
DEALLOCATE c;

-- columns in the tables that are not in the spec (kept; check whether they are still needed)
DECLARE @extra nvarchar(max);
SELECT @extra = STUFF((
    SELECT N', ' + t.name + N'.' + c.name
    FROM sys.tables t
    JOIN sys.columns c ON c.object_id = t.object_id
    WHERE t.schema_id = SCHEMA_ID(N'dbo')
      AND t.name IN (SELECT DISTINCT tbl FROM @spec)
      AND NOT EXISTS (SELECT 1 FROM @spec s WHERE s.tbl = t.name AND s.col = c.name)
    ORDER BY t.name, c.column_id
    FOR XML PATH(''), TYPE).value('.', 'nvarchar(max)'), 1, 2, N'');
IF @extra IS NOT NULL
    PRINT N'EXTRA    not in the spec (kept): ' + @extra;

COMMIT TRANSACTION;
GO
