/*
    Foundation Group - child tables for NetSuite master data (FROM tasks,
    NetSuite connector). Adds only the child tables, next to the existing
    header tables; a table that already exists is skipped.

    dbo.tb_NetSuite_Vendor_AddressBook        vendor/addressBook/items
    dbo.tb_NetSuite_Classification_Subsidiary classification/subsidiary/items
    dbo.tb_NetSuite_Department_Subsidiary     department/subsidiary/items
    dbo.tb_NetSuite_Location_Subsidiary       location/subsidiary/items
    dbo.tb_NetSuite_Account_Subsidiary        account/subsidiary/items

    Column names are the NetSuite REST field names. A reference field is stored
    as <field>Id + <field>RefName (the values on the record itself; the
    connector does not need to expand the referenced record). Timestamps
    (lastModifiedDate, dateCreated) come as 'YYYY-MM-DDThh:mm:ssZ' and are UTC.
    A child row links to its parent through BPA_ParentID = parent BPA_EntryID,
    and holds the parent's NetSuite id in <record>Id.

    Runs in a single transaction.

    Generated by tools/netsuite_masterdata.py: change the spec there and
    regenerate. See docs/foundation_masterdata.md.
*/
SET XACT_ABORT ON;
SET NOCOUNT ON;
GO
BEGIN TRANSACTION;

-- vendor/addressBook/items -> dbo.tb_NetSuite_Vendor_AddressBook: one row per line
IF OBJECT_ID(N'dbo.tb_NetSuite_Vendor_AddressBook', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.tb_NetSuite_Vendor_AddressBook (
        -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
        BPA_Origin                  nvarchar(50) NULL,
        BPA_Direction               nvarchar(50) NULL,
        BPA_Company                 nvarchar(50) NULL,
        BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Vendor_AddressBook_EntryID DEFAULT (newsequentialid()),
        BPA_ParentID                uniqueidentifier NULL,
        BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Vendor_AddressBook_Status DEFAULT ((0)),
        BPA_Reference               nvarchar(50) NULL,
        BPA_Reference_Description   nvarchar(100) NULL,
        BPA_Reference2              nvarchar(50) NULL,
        BPA_Reference2_Description  nvarchar(100) NULL,
        BPA_Action                  nvarchar(1) NULL,
        BPA_ReturnedID              nvarchar(50) NULL,
        BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Vendor_AddressBook_Syscreated DEFAULT (getdate()),
        BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Vendor_AddressBook_Sysmodified DEFAULT (getdate()),
        BPA_Syscreator              nvarchar(50) NULL,
        BPA_Error                   nvarchar(max) NULL,
        BPA_Error_Extended          nvarchar(max) NULL,
        BPA_Description             nvarchar(255) NULL,
        BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Vendor_AddressBook_Failcount DEFAULT ((0)),
        BPA_Orig_Entryid            uniqueidentifier NULL,
        BPA_TaskInstanceID          int NULL,
        BPA_TaskID                  int NULL,

        -- Parent: BPA_ParentID = tb_NetSuite_Vendor.BPA_EntryID
        vendorId                    nvarchar(100) NOT NULL,     -- vendor/id (the parent's NetSuite id)

        -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
        addressBookId               int NOT NULL,               -- address book line id
        label                       nvarchar(255) NULL,
        defaultBilling              bit NULL,
        defaultShipping             bit NULL,
        addressBookAddress_text     nvarchar(1000) NULL,        -- full address as text
        addressee                   nvarchar(255) NULL,
        attention                   nvarchar(255) NULL,
        addr1                       nvarchar(255) NULL,
        addr2                       nvarchar(255) NULL,
        addr3                       nvarchar(255) NULL,
        city                        nvarchar(100) NULL,
        state                       nvarchar(100) NULL,
        zip                         nvarchar(50) NULL,
        countryId                   nvarchar(10) NULL,          -- GB, NL, BE, ...
        countryRefName              nvarchar(100) NULL,
        addrPhone                   nvarchar(50) NULL,
        override                    bit NULL,
        CONSTRAINT PK_tb_NetSuite_Vendor_AddressBook PRIMARY KEY CLUSTERED (BPA_EntryID)
    );
    CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Vendor_AddressBook_BPA_ParentID ON dbo.tb_NetSuite_Vendor_AddressBook (BPA_ParentID);
    CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Vendor_AddressBook_vendorId ON dbo.tb_NetSuite_Vendor_AddressBook (vendorId, addressBookId);
    PRINT N'Created  dbo.tb_NetSuite_Vendor_AddressBook';
END
ELSE
    PRINT N'Skipped  dbo.tb_NetSuite_Vendor_AddressBook (already exists)';

-- classification/subsidiary/items -> dbo.tb_NetSuite_Classification_Subsidiary: one row per selected subsidiary
IF OBJECT_ID(N'dbo.tb_NetSuite_Classification_Subsidiary', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.tb_NetSuite_Classification_Subsidiary (
        -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
        BPA_Origin                  nvarchar(50) NULL,
        BPA_Direction               nvarchar(50) NULL,
        BPA_Company                 nvarchar(50) NULL,
        BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Classification_Subsidiary_EntryID DEFAULT (newsequentialid()),
        BPA_ParentID                uniqueidentifier NULL,
        BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Classification_Subsidiary_Status DEFAULT ((0)),
        BPA_Reference               nvarchar(50) NULL,
        BPA_Reference_Description   nvarchar(100) NULL,
        BPA_Reference2              nvarchar(50) NULL,
        BPA_Reference2_Description  nvarchar(100) NULL,
        BPA_Action                  nvarchar(1) NULL,
        BPA_ReturnedID              nvarchar(50) NULL,
        BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Classification_Subsidiary_Syscreated DEFAULT (getdate()),
        BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Classification_Subsidiary_Sysmodified DEFAULT (getdate()),
        BPA_Syscreator              nvarchar(50) NULL,
        BPA_Error                   nvarchar(max) NULL,
        BPA_Error_Extended          nvarchar(max) NULL,
        BPA_Description             nvarchar(255) NULL,
        BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Classification_Subsidiary_Failcount DEFAULT ((0)),
        BPA_Orig_Entryid            uniqueidentifier NULL,
        BPA_TaskInstanceID          int NULL,
        BPA_TaskID                  int NULL,

        -- Parent: BPA_ParentID = tb_NetSuite_Classification.BPA_EntryID
        classificationId            nvarchar(100) NOT NULL,     -- classification/id (the parent's NetSuite id)

        -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
        subsidiaryId                nvarchar(100) NULL,
        subsidiaryRefName           nvarchar(400) NULL,
        CONSTRAINT PK_tb_NetSuite_Classification_Subsidiary PRIMARY KEY CLUSTERED (BPA_EntryID)
    );
    CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Classification_Subsidiary_BPA_ParentID ON dbo.tb_NetSuite_Classification_Subsidiary (BPA_ParentID);
    CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Classification_Subsidiary_classificationId ON dbo.tb_NetSuite_Classification_Subsidiary (classificationId, subsidiaryId);
    PRINT N'Created  dbo.tb_NetSuite_Classification_Subsidiary';
END
ELSE
    PRINT N'Skipped  dbo.tb_NetSuite_Classification_Subsidiary (already exists)';

-- department/subsidiary/items -> dbo.tb_NetSuite_Department_Subsidiary: one row per selected subsidiary
IF OBJECT_ID(N'dbo.tb_NetSuite_Department_Subsidiary', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.tb_NetSuite_Department_Subsidiary (
        -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
        BPA_Origin                  nvarchar(50) NULL,
        BPA_Direction               nvarchar(50) NULL,
        BPA_Company                 nvarchar(50) NULL,
        BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Department_Subsidiary_EntryID DEFAULT (newsequentialid()),
        BPA_ParentID                uniqueidentifier NULL,
        BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Department_Subsidiary_Status DEFAULT ((0)),
        BPA_Reference               nvarchar(50) NULL,
        BPA_Reference_Description   nvarchar(100) NULL,
        BPA_Reference2              nvarchar(50) NULL,
        BPA_Reference2_Description  nvarchar(100) NULL,
        BPA_Action                  nvarchar(1) NULL,
        BPA_ReturnedID              nvarchar(50) NULL,
        BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Department_Subsidiary_Syscreated DEFAULT (getdate()),
        BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Department_Subsidiary_Sysmodified DEFAULT (getdate()),
        BPA_Syscreator              nvarchar(50) NULL,
        BPA_Error                   nvarchar(max) NULL,
        BPA_Error_Extended          nvarchar(max) NULL,
        BPA_Description             nvarchar(255) NULL,
        BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Department_Subsidiary_Failcount DEFAULT ((0)),
        BPA_Orig_Entryid            uniqueidentifier NULL,
        BPA_TaskInstanceID          int NULL,
        BPA_TaskID                  int NULL,

        -- Parent: BPA_ParentID = tb_NetSuite_Department.BPA_EntryID
        departmentId                nvarchar(100) NOT NULL,     -- department/id (the parent's NetSuite id)

        -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
        subsidiaryId                nvarchar(100) NULL,
        subsidiaryRefName           nvarchar(400) NULL,
        CONSTRAINT PK_tb_NetSuite_Department_Subsidiary PRIMARY KEY CLUSTERED (BPA_EntryID)
    );
    CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Department_Subsidiary_BPA_ParentID ON dbo.tb_NetSuite_Department_Subsidiary (BPA_ParentID);
    CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Department_Subsidiary_departmentId ON dbo.tb_NetSuite_Department_Subsidiary (departmentId, subsidiaryId);
    PRINT N'Created  dbo.tb_NetSuite_Department_Subsidiary';
END
ELSE
    PRINT N'Skipped  dbo.tb_NetSuite_Department_Subsidiary (already exists)';

-- location/subsidiary/items -> dbo.tb_NetSuite_Location_Subsidiary: one row per selected subsidiary
IF OBJECT_ID(N'dbo.tb_NetSuite_Location_Subsidiary', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.tb_NetSuite_Location_Subsidiary (
        -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
        BPA_Origin                  nvarchar(50) NULL,
        BPA_Direction               nvarchar(50) NULL,
        BPA_Company                 nvarchar(50) NULL,
        BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Location_Subsidiary_EntryID DEFAULT (newsequentialid()),
        BPA_ParentID                uniqueidentifier NULL,
        BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Location_Subsidiary_Status DEFAULT ((0)),
        BPA_Reference               nvarchar(50) NULL,
        BPA_Reference_Description   nvarchar(100) NULL,
        BPA_Reference2              nvarchar(50) NULL,
        BPA_Reference2_Description  nvarchar(100) NULL,
        BPA_Action                  nvarchar(1) NULL,
        BPA_ReturnedID              nvarchar(50) NULL,
        BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Location_Subsidiary_Syscreated DEFAULT (getdate()),
        BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Location_Subsidiary_Sysmodified DEFAULT (getdate()),
        BPA_Syscreator              nvarchar(50) NULL,
        BPA_Error                   nvarchar(max) NULL,
        BPA_Error_Extended          nvarchar(max) NULL,
        BPA_Description             nvarchar(255) NULL,
        BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Location_Subsidiary_Failcount DEFAULT ((0)),
        BPA_Orig_Entryid            uniqueidentifier NULL,
        BPA_TaskInstanceID          int NULL,
        BPA_TaskID                  int NULL,

        -- Parent: BPA_ParentID = tb_NetSuite_Location.BPA_EntryID
        locationId                  nvarchar(100) NOT NULL,     -- location/id (the parent's NetSuite id)

        -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
        subsidiaryId                nvarchar(100) NULL,
        subsidiaryRefName           nvarchar(400) NULL,
        CONSTRAINT PK_tb_NetSuite_Location_Subsidiary PRIMARY KEY CLUSTERED (BPA_EntryID)
    );
    CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Location_Subsidiary_BPA_ParentID ON dbo.tb_NetSuite_Location_Subsidiary (BPA_ParentID);
    CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Location_Subsidiary_locationId ON dbo.tb_NetSuite_Location_Subsidiary (locationId, subsidiaryId);
    PRINT N'Created  dbo.tb_NetSuite_Location_Subsidiary';
END
ELSE
    PRINT N'Skipped  dbo.tb_NetSuite_Location_Subsidiary (already exists)';

-- account/subsidiary/items -> dbo.tb_NetSuite_Account_Subsidiary: one row per selected subsidiary
IF OBJECT_ID(N'dbo.tb_NetSuite_Account_Subsidiary', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.tb_NetSuite_Account_Subsidiary (
        -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
        BPA_Origin                  nvarchar(50) NULL,
        BPA_Direction               nvarchar(50) NULL,
        BPA_Company                 nvarchar(50) NULL,
        BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Account_Subsidiary_EntryID DEFAULT (newsequentialid()),
        BPA_ParentID                uniqueidentifier NULL,
        BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Account_Subsidiary_Status DEFAULT ((0)),
        BPA_Reference               nvarchar(50) NULL,
        BPA_Reference_Description   nvarchar(100) NULL,
        BPA_Reference2              nvarchar(50) NULL,
        BPA_Reference2_Description  nvarchar(100) NULL,
        BPA_Action                  nvarchar(1) NULL,
        BPA_ReturnedID              nvarchar(50) NULL,
        BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Account_Subsidiary_Syscreated DEFAULT (getdate()),
        BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Account_Subsidiary_Sysmodified DEFAULT (getdate()),
        BPA_Syscreator              nvarchar(50) NULL,
        BPA_Error                   nvarchar(max) NULL,
        BPA_Error_Extended          nvarchar(max) NULL,
        BPA_Description             nvarchar(255) NULL,
        BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Account_Subsidiary_Failcount DEFAULT ((0)),
        BPA_Orig_Entryid            uniqueidentifier NULL,
        BPA_TaskInstanceID          int NULL,
        BPA_TaskID                  int NULL,

        -- Parent: BPA_ParentID = tb_NetSuite_Account.BPA_EntryID
        accountId                   nvarchar(100) NOT NULL,     -- account/id (the parent's NetSuite id)

        -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
        subsidiaryId                nvarchar(100) NULL,
        subsidiaryRefName           nvarchar(400) NULL,
        CONSTRAINT PK_tb_NetSuite_Account_Subsidiary PRIMARY KEY CLUSTERED (BPA_EntryID)
    );
    CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Account_Subsidiary_BPA_ParentID ON dbo.tb_NetSuite_Account_Subsidiary (BPA_ParentID);
    CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Account_Subsidiary_accountId ON dbo.tb_NetSuite_Account_Subsidiary (accountId, subsidiaryId);
    PRINT N'Created  dbo.tb_NetSuite_Account_Subsidiary';
END
ELSE
    PRINT N'Skipped  dbo.tb_NetSuite_Account_Subsidiary (already exists)';

COMMIT TRANSACTION;
GO
