/*
    Foundation Group - child tables for NetSuite vendor bills (FROM tasks,
    NetSuite connector). Adds only the child tables, next to the existing
    header tables; a table that already exists is skipped.

    dbo.tb_Netsuite_VendorBill_Expense        vendorBill/expense/items
    dbo.tb_Netsuite_VendorBill_Item           vendorBill/item/items

    Column names are the NetSuite REST field names. A reference field is stored
    as <field>Id + <field>RefName (the values on the record itself; the
    connector does not need to expand the referenced record). Timestamps
    (lastModifiedDate, dateCreated) come as 'YYYY-MM-DDThh:mm:ssZ' and are UTC.
    A child row links to its parent through BPA_ParentID = parent BPA_EntryID,
    and holds the parent's NetSuite id in <record>Id.

    Runs in a single transaction.

    Generated by tools/netsuite_masterdata.py: change the spec there and
    regenerate. See docs/foundation_masterdata.md and the validation report
    docs/foundation_vendorbill_validation.md.
*/
SET XACT_ABORT ON;
SET NOCOUNT ON;
GO
BEGIN TRANSACTION;

-- vendorBill/expense/items -> dbo.tb_Netsuite_VendorBill_Expense: one row per line
IF OBJECT_ID(N'dbo.tb_Netsuite_VendorBill_Expense', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.tb_Netsuite_VendorBill_Expense (
        -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
        BPA_Origin                  nvarchar(50) NULL,
        BPA_Direction               nvarchar(50) NULL,
        BPA_Company                 nvarchar(50) NULL,
        BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_EntryID DEFAULT (newsequentialid()),
        BPA_ParentID                uniqueidentifier NULL,
        BPA_Status                  int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Status DEFAULT ((0)),
        BPA_Reference               nvarchar(50) NULL,
        BPA_Reference_Description   nvarchar(100) NULL,
        BPA_Reference2              nvarchar(50) NULL,
        BPA_Reference2_Description  nvarchar(100) NULL,
        BPA_Action                  nvarchar(1) NULL,
        BPA_ReturnedID              nvarchar(50) NULL,
        BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Syscreated DEFAULT (getdate()),
        BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Sysmodified DEFAULT (getdate()),
        BPA_Syscreator              nvarchar(50) NULL,
        BPA_Error                   nvarchar(max) NULL,
        BPA_Error_Extended          nvarchar(max) NULL,
        BPA_Description             nvarchar(255) NULL,
        BPA_Failcount               int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Failcount DEFAULT ((0)),
        BPA_Orig_Entryid            uniqueidentifier NULL,
        BPA_TaskInstanceID          int NULL,
        BPA_TaskID                  int NULL,

        -- Parent: BPA_ParentID = tb_Netsuite_VendorBill.BPA_EntryID
        vendorBillId                nvarchar(100) NOT NULL,     -- vendorBill/id (the parent's NetSuite id)

        -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
        line                        int NOT NULL,
        accountId                   nvarchar(100) NULL,
        accountRefName              nvarchar(400) NULL,
        amount                      decimal(19,4) NULL,         -- net
        taxCodeId                   nvarchar(100) NULL,
        taxCodeRefName              nvarchar(100) NULL,
        taxRate1                    decimal(9,4) NULL,          -- 1.0% -> 1.0000
        tax1Amt                     decimal(19,4) NULL,
        grossAmt                    decimal(19,4) NULL,
        memo                        nvarchar(4000) NULL,
        departmentId                nvarchar(100) NULL,
        departmentRefName           nvarchar(400) NULL,
        classId                     nvarchar(100) NULL,
        classRefName                nvarchar(400) NULL,
        locationId                  nvarchar(100) NULL,
        locationRefName             nvarchar(400) NULL,
        customerId                  nvarchar(100) NULL,
        customerRefName             nvarchar(400) NULL,
        isBillable                  bit NULL,
        categoryId                  nvarchar(100) NULL,
        categoryRefName             nvarchar(400) NULL,
        amortizationSchedId         nvarchar(100) NULL,
        amortizationSchedRefName    nvarchar(400) NULL,
        amortizStartDate            date NULL,
        amortizationEndDate         date NULL,
        amortizationResidual        nvarchar(100) NULL,
        orderDoc                    nvarchar(100) NULL,         -- linked purchase order
        orderLine                   nvarchar(50) NULL,
        CONSTRAINT PK_tb_Netsuite_VendorBill_Expense PRIMARY KEY CLUSTERED (BPA_EntryID)
    );
    CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Expense_BPA_ParentID ON dbo.tb_Netsuite_VendorBill_Expense (BPA_ParentID);
    CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Expense_vendorBillId ON dbo.tb_Netsuite_VendorBill_Expense (vendorBillId, line);
    PRINT N'Created  dbo.tb_Netsuite_VendorBill_Expense';
END
ELSE
    PRINT N'Skipped  dbo.tb_Netsuite_VendorBill_Expense (already exists)';

-- vendorBill/item/items -> dbo.tb_Netsuite_VendorBill_Item: one row per line
IF OBJECT_ID(N'dbo.tb_Netsuite_VendorBill_Item', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.tb_Netsuite_VendorBill_Item (
        -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
        BPA_Origin                  nvarchar(50) NULL,
        BPA_Direction               nvarchar(50) NULL,
        BPA_Company                 nvarchar(50) NULL,
        BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_EntryID DEFAULT (newsequentialid()),
        BPA_ParentID                uniqueidentifier NULL,
        BPA_Status                  int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Status DEFAULT ((0)),
        BPA_Reference               nvarchar(50) NULL,
        BPA_Reference_Description   nvarchar(100) NULL,
        BPA_Reference2              nvarchar(50) NULL,
        BPA_Reference2_Description  nvarchar(100) NULL,
        BPA_Action                  nvarchar(1) NULL,
        BPA_ReturnedID              nvarchar(50) NULL,
        BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Syscreated DEFAULT (getdate()),
        BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Sysmodified DEFAULT (getdate()),
        BPA_Syscreator              nvarchar(50) NULL,
        BPA_Error                   nvarchar(max) NULL,
        BPA_Error_Extended          nvarchar(max) NULL,
        BPA_Description             nvarchar(255) NULL,
        BPA_Failcount               int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Failcount DEFAULT ((0)),
        BPA_Orig_Entryid            uniqueidentifier NULL,
        BPA_TaskInstanceID          int NULL,
        BPA_TaskID                  int NULL,

        -- Parent: BPA_ParentID = tb_Netsuite_VendorBill.BPA_EntryID
        vendorBillId                nvarchar(100) NOT NULL,     -- vendorBill/id (the parent's NetSuite id)

        -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
        line                        int NOT NULL,
        uniqueKey                   int NULL,                   -- line unique key
        itemId                      nvarchar(100) NULL,
        itemRefName                 nvarchar(400) NULL,
        vendorName                  nvarchar(255) NULL,         -- vendor's item code
        description                 nvarchar(4000) NULL,
        quantity                    decimal(28,10) NULL,
        units                       nvarchar(100) NULL,
        rate                        decimal(28,10) NULL,
        amount                      decimal(19,4) NULL,         -- net
        taxCodeId                   nvarchar(100) NULL,
        taxCodeRefName              nvarchar(100) NULL,
        taxRate1                    decimal(9,4) NULL,
        tax1Amt                     decimal(19,4) NULL,
        grossAmt                    decimal(19,4) NULL,
        departmentId                nvarchar(100) NULL,
        departmentRefName           nvarchar(400) NULL,
        classId                     nvarchar(100) NULL,
        classRefName                nvarchar(400) NULL,
        customerId                  nvarchar(100) NULL,
        customerRefName             nvarchar(400) NULL,
        isBillable                  bit NULL,
        orderLine                   int NULL,                   -- linked purchase order line
        amortizStartDate            date NULL,
        amortizationEndDate         date NULL,
        amortizationResidual        nvarchar(100) NULL,
        CONSTRAINT PK_tb_Netsuite_VendorBill_Item PRIMARY KEY CLUSTERED (BPA_EntryID)
    );
    CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Item_BPA_ParentID ON dbo.tb_Netsuite_VendorBill_Item (BPA_ParentID);
    CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Item_vendorBillId ON dbo.tb_Netsuite_VendorBill_Item (vendorBillId, line);
    PRINT N'Created  dbo.tb_Netsuite_VendorBill_Item';
END
ELSE
    PRINT N'Skipped  dbo.tb_Netsuite_VendorBill_Item (already exists)';

COMMIT TRANSACTION;
GO
