/*
    Foundation Group - typed views over the NetSuite staging tables whose number
    columns are stored as text (the connector writes numbers with the decimal
    separator of the server it runs on, e.g. 907,5).

    Each view returns every column of its table; number columns are converted with
    TRY_CONVERT(decimal(p,s), REPLACE(<column>, ',', '.')), with a fallback through
    float for scientific notation (1E-05). Replacing ',' is safe: the connector
    never writes a thousands separator. A value that still does not convert
    becomes NULL; find those with the check query at the end.

    Read the data through these views, not the tables.

    Generated by tools/netsuite_masterdata.py sql views --group vendorbill.
*/
GO
CREATE OR ALTER VIEW dbo.vw_Netsuite_VendorBill
AS
SELECT
    BPA_Origin,
    BPA_Direction,
    BPA_Company,
    BPA_EntryID,
    BPA_ParentID,
    BPA_Status,
    BPA_Reference,
    BPA_Reference_Description,
    BPA_Reference2,
    BPA_Reference2_Description,
    BPA_Action,
    BPA_ReturnedID,
    BPA_Syscreated,
    BPA_Sysmodified,
    BPA_Syscreator,
    BPA_Error,
    BPA_Error_Extended,
    BPA_Description,
    BPA_Failcount,
    BPA_Orig_Entryid,
    BPA_TaskInstanceID,
    BPA_TaskID,
    id,
    externalId,
    tranId,
    transactionNumber,
    tranDate,
    dueDate,
    createdDate,
    lastModifiedDate,
    entityId,
    entityRefName,
    subsidiaryId,
    subsidiaryRefName,
    currencyId,
    currencyRefName,
    accountId,
    accountRefName,
    postingPeriodId,
    postingPeriodRefName,
    termsId,
    termsRefName,
    approvalStatusId,
    approvalStatusRefName,
    statusId,
    statusRefName,
    departmentId,
    departmentRefName,
    classId,
    classRefName,
    locationId,
    locationRefName,
    exchangeRate = COALESCE(TRY_CONVERT(decimal(28,10), REPLACE(exchangeRate, N',', N'.')), TRY_CONVERT(decimal(28,10), TRY_CONVERT(float, REPLACE(exchangeRate, N',', N'.')))),
    total = COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(total, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(total, N',', N'.')))),
    userTotal = COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(userTotal, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(userTotal, N',', N'.')))),
    taxTotal = COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(taxTotal, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(taxTotal, N',', N'.')))),
    discountAmount = COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(discountAmount, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(discountAmount, N',', N'.')))),
    discountDate,
    memo,
    documentStatus,
    paymentHold,
    received,
    toBePrinted,
    vatRegNum,
    billAddressee,
    billAttention,
    billAddr1,
    billAddr2,
    billAddr3,
    billCity,
    billState,
    billZip,
    billCountryId,
    billCountryRefName,
    billAddress,
    cseg_bit_4weeksId,
    cseg_bit_4weeksRefName,
    custbody_document_date,
    custbody_establishment_code,
    custbody_15529_vendor_entity_bankId,
    custbody_15529_vendor_entity_bankRefName,
    custbody_11187_pref_entity_bankId,
    custbody_11187_pref_entity_bankRefName,
    custbody_9997_is_for_ep_eft,
    custbody_11724_pay_bank_fees,
    custbody_stc_amount_after_discount = COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(custbody_stc_amount_after_discount, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(custbody_stc_amount_after_discount, N',', N'.')))),
    custbody_stc_tax_after_discount = COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(custbody_stc_tax_after_discount, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(custbody_stc_tax_after_discount, N',', N'.')))),
    custbody_stc_total_after_discount = COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(custbody_stc_total_after_discount, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(custbody_stc_total_after_discount, N',', N'.')))),
    custbody_stc_discountpercent = COALESCE(TRY_CONVERT(decimal(9,4), REPLACE(custbody_stc_discountpercent, N',', N'.')), TRY_CONVERT(decimal(9,4), TRY_CONVERT(float, REPLACE(custbody_stc_discountpercent, N',', N'.')))),
    custbody_stc_daysuntilexpiry,
    custbody_stc_payment_transaction_id,
    custbody_bit_zonalurl
FROM dbo.tb_Netsuite_VendorBill;
GO

CREATE OR ALTER VIEW dbo.vw_Netsuite_VendorBill_Expense
AS
SELECT
    BPA_Origin,
    BPA_Direction,
    BPA_Company,
    BPA_EntryID,
    BPA_ParentID,
    BPA_Status,
    BPA_Reference,
    BPA_Reference_Description,
    BPA_Reference2,
    BPA_Reference2_Description,
    BPA_Action,
    BPA_ReturnedID,
    BPA_Syscreated,
    BPA_Sysmodified,
    BPA_Syscreator,
    BPA_Error,
    BPA_Error_Extended,
    BPA_Description,
    BPA_Failcount,
    BPA_Orig_Entryid,
    BPA_TaskInstanceID,
    BPA_TaskID,
    vendorBillId,
    line,
    accountId,
    accountRefName,
    amount = COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(amount, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(amount, N',', N'.')))),
    taxCodeId,
    taxCodeRefName,
    taxRate1 = COALESCE(TRY_CONVERT(decimal(9,4), REPLACE(taxRate1, N',', N'.')), TRY_CONVERT(decimal(9,4), TRY_CONVERT(float, REPLACE(taxRate1, N',', N'.')))),
    tax1Amt = COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(tax1Amt, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(tax1Amt, N',', N'.')))),
    grossAmt = COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(grossAmt, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(grossAmt, N',', N'.')))),
    memo,
    departmentId,
    departmentRefName,
    classId,
    classRefName,
    locationId,
    locationRefName,
    customerId,
    customerRefName,
    isBillable,
    categoryId,
    categoryRefName,
    amortizationSchedId,
    amortizationSchedRefName,
    amortizStartDate,
    amortizationEndDate,
    amortizationResidual,
    amortizationType,
    scheduleType,
    orderDoc,
    orderLine
FROM dbo.tb_Netsuite_VendorBill_Expense;
GO

CREATE OR ALTER VIEW dbo.vw_Netsuite_VendorBill_Item
AS
SELECT
    BPA_Origin,
    BPA_Direction,
    BPA_Company,
    BPA_EntryID,
    BPA_ParentID,
    BPA_Status,
    BPA_Reference,
    BPA_Reference_Description,
    BPA_Reference2,
    BPA_Reference2_Description,
    BPA_Action,
    BPA_ReturnedID,
    BPA_Syscreated,
    BPA_Sysmodified,
    BPA_Syscreator,
    BPA_Error,
    BPA_Error_Extended,
    BPA_Description,
    BPA_Failcount,
    BPA_Orig_Entryid,
    BPA_TaskInstanceID,
    BPA_TaskID,
    vendorBillId,
    line,
    uniqueKey,
    itemId,
    itemRefName,
    vendorName,
    description,
    quantity = COALESCE(TRY_CONVERT(decimal(28,10), REPLACE(quantity, N',', N'.')), TRY_CONVERT(decimal(28,10), TRY_CONVERT(float, REPLACE(quantity, N',', N'.')))),
    units,
    rate = COALESCE(TRY_CONVERT(decimal(28,10), REPLACE(rate, N',', N'.')), TRY_CONVERT(decimal(28,10), TRY_CONVERT(float, REPLACE(rate, N',', N'.')))),
    amount = COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(amount, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(amount, N',', N'.')))),
    taxCodeId,
    taxCodeRefName,
    taxRate1 = COALESCE(TRY_CONVERT(decimal(9,4), REPLACE(taxRate1, N',', N'.')), TRY_CONVERT(decimal(9,4), TRY_CONVERT(float, REPLACE(taxRate1, N',', N'.')))),
    tax1Amt = COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(tax1Amt, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(tax1Amt, N',', N'.')))),
    grossAmt = COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(grossAmt, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(grossAmt, N',', N'.')))),
    departmentId,
    departmentRefName,
    classId,
    classRefName,
    customerId,
    customerRefName,
    isBillable,
    orderLine,
    amortizStartDate,
    amortizationEndDate,
    amortizationResidual
FROM dbo.tb_Netsuite_VendorBill_Item;
GO

/* Check: values that do not convert (should return no rows)
SELECT N'tb_Netsuite_VendorBill' AS tbl, N'exchangeRate' AS col, BPA_EntryID, exchangeRate AS value FROM dbo.tb_Netsuite_VendorBill WHERE exchangeRate IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(28,10), REPLACE(exchangeRate, N',', N'.')), TRY_CONVERT(decimal(28,10), TRY_CONVERT(float, REPLACE(exchangeRate, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill' AS tbl, N'total' AS col, BPA_EntryID, total AS value FROM dbo.tb_Netsuite_VendorBill WHERE total IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(total, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(total, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill' AS tbl, N'userTotal' AS col, BPA_EntryID, userTotal AS value FROM dbo.tb_Netsuite_VendorBill WHERE userTotal IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(userTotal, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(userTotal, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill' AS tbl, N'taxTotal' AS col, BPA_EntryID, taxTotal AS value FROM dbo.tb_Netsuite_VendorBill WHERE taxTotal IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(taxTotal, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(taxTotal, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill' AS tbl, N'discountAmount' AS col, BPA_EntryID, discountAmount AS value FROM dbo.tb_Netsuite_VendorBill WHERE discountAmount IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(discountAmount, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(discountAmount, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill' AS tbl, N'custbody_stc_amount_after_discount' AS col, BPA_EntryID, custbody_stc_amount_after_discount AS value FROM dbo.tb_Netsuite_VendorBill WHERE custbody_stc_amount_after_discount IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(custbody_stc_amount_after_discount, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(custbody_stc_amount_after_discount, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill' AS tbl, N'custbody_stc_tax_after_discount' AS col, BPA_EntryID, custbody_stc_tax_after_discount AS value FROM dbo.tb_Netsuite_VendorBill WHERE custbody_stc_tax_after_discount IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(custbody_stc_tax_after_discount, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(custbody_stc_tax_after_discount, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill' AS tbl, N'custbody_stc_total_after_discount' AS col, BPA_EntryID, custbody_stc_total_after_discount AS value FROM dbo.tb_Netsuite_VendorBill WHERE custbody_stc_total_after_discount IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(custbody_stc_total_after_discount, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(custbody_stc_total_after_discount, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill' AS tbl, N'custbody_stc_discountpercent' AS col, BPA_EntryID, custbody_stc_discountpercent AS value FROM dbo.tb_Netsuite_VendorBill WHERE custbody_stc_discountpercent IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(9,4), REPLACE(custbody_stc_discountpercent, N',', N'.')), TRY_CONVERT(decimal(9,4), TRY_CONVERT(float, REPLACE(custbody_stc_discountpercent, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill_Expense' AS tbl, N'amount' AS col, BPA_EntryID, amount AS value FROM dbo.tb_Netsuite_VendorBill_Expense WHERE amount IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(amount, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(amount, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill_Expense' AS tbl, N'taxRate1' AS col, BPA_EntryID, taxRate1 AS value FROM dbo.tb_Netsuite_VendorBill_Expense WHERE taxRate1 IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(9,4), REPLACE(taxRate1, N',', N'.')), TRY_CONVERT(decimal(9,4), TRY_CONVERT(float, REPLACE(taxRate1, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill_Expense' AS tbl, N'tax1Amt' AS col, BPA_EntryID, tax1Amt AS value FROM dbo.tb_Netsuite_VendorBill_Expense WHERE tax1Amt IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(tax1Amt, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(tax1Amt, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill_Expense' AS tbl, N'grossAmt' AS col, BPA_EntryID, grossAmt AS value FROM dbo.tb_Netsuite_VendorBill_Expense WHERE grossAmt IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(grossAmt, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(grossAmt, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill_Item' AS tbl, N'quantity' AS col, BPA_EntryID, quantity AS value FROM dbo.tb_Netsuite_VendorBill_Item WHERE quantity IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(28,10), REPLACE(quantity, N',', N'.')), TRY_CONVERT(decimal(28,10), TRY_CONVERT(float, REPLACE(quantity, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill_Item' AS tbl, N'rate' AS col, BPA_EntryID, rate AS value FROM dbo.tb_Netsuite_VendorBill_Item WHERE rate IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(28,10), REPLACE(rate, N',', N'.')), TRY_CONVERT(decimal(28,10), TRY_CONVERT(float, REPLACE(rate, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill_Item' AS tbl, N'amount' AS col, BPA_EntryID, amount AS value FROM dbo.tb_Netsuite_VendorBill_Item WHERE amount IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(amount, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(amount, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill_Item' AS tbl, N'taxRate1' AS col, BPA_EntryID, taxRate1 AS value FROM dbo.tb_Netsuite_VendorBill_Item WHERE taxRate1 IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(9,4), REPLACE(taxRate1, N',', N'.')), TRY_CONVERT(decimal(9,4), TRY_CONVERT(float, REPLACE(taxRate1, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill_Item' AS tbl, N'tax1Amt' AS col, BPA_EntryID, tax1Amt AS value FROM dbo.tb_Netsuite_VendorBill_Item WHERE tax1Amt IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(tax1Amt, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(tax1Amt, N',', N'.')))) IS NULL
UNION ALL
SELECT N'tb_Netsuite_VendorBill_Item' AS tbl, N'grossAmt' AS col, BPA_EntryID, grossAmt AS value FROM dbo.tb_Netsuite_VendorBill_Item WHERE grossAmt IS NOT NULL AND COALESCE(TRY_CONVERT(decimal(19,4), REPLACE(grossAmt, N',', N'.')), TRY_CONVERT(decimal(19,4), TRY_CONVERT(float, REPLACE(grossAmt, N',', N'.')))) IS NULL;
*/
