/*
    Foundation Group - staging tables for NetSuite vendor bills (FROM tasks,
    NetSuite connector): every table, header and child. Compare your own
    tables with it: tools/netsuite_masterdata.py check-ddl.

    dbo.tb_Netsuite_VendorBill                vendorBill
    dbo.tb_Netsuite_VendorBill_Expense        vendorBill/expense/items
    dbo.tb_Netsuite_VendorBill_Item           vendorBill/item/items
    dbo.tb_Netsuite_VendorBill_GLImpactChangesvendorBill/glImpactChanges/items

    Column names are the NetSuite REST field names. A reference field is stored
    as <field>Id + <field>RefName (the values on the record itself; the
    connector does not need to expand the referenced record). Timestamps
    (lastModifiedDate, dateCreated) come as 'YYYY-MM-DDThh:mm:ssZ' and are UTC.
    A child row links to its parent through BPA_ParentID = parent BPA_EntryID,
    and holds the parent's NetSuite id in <record>Id.

    Existing tables are renamed to <table>_bak (constraints and indexes included)
    before the new ones are created; drop the _bak tables once loading works.
    Stops without changes if a _bak table already exists.
    Runs in a single transaction.

    Generated by tools/netsuite_masterdata.py: change the spec there and
    regenerate. See docs/foundation_masterdata.md and the validation report
    docs/foundation_vendorbill_validation.md.
*/
SET XACT_ABORT ON;
SET NOCOUNT ON;
IF OBJECT_ID(N'tempdb..#rebuild') IS NOT NULL DROP PROCEDURE #rebuild;
GO
-- Renames an existing table to <table>_bak (constraints and indexes get a _bak
-- suffix too), so the new definition can be created without losing data.
CREATE PROCEDURE #rebuild @table sysname AS
BEGIN
    DECLARE @bak sysname = @table + N'_bak', @old sysname, @new sysname, @obj nvarchar(300), @msg nvarchar(400);
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@table), N'U') IS NULL RETURN;
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@bak), N'U') IS NOT NULL
    BEGIN
        SET @msg = N'dbo.' + @bak + N' already exists; drop or rename it first.';
        THROW 50001, @msg, 1;
    END
    SET @obj = N'dbo.' + QUOTENAME(@table);
    EXEC sys.sp_rename @objname = @obj, @newname = @bak, @objtype = N'OBJECT';
    PRINT N'Renamed  dbo.' + @table + N' -> ' + @bak;
    DECLARE con CURSOR LOCAL FAST_FORWARD FOR
        SELECT name FROM sys.objects
        WHERE parent_object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@bak)) AND type IN ('PK', 'UQ', 'D', 'C', 'F');
    OPEN con;
    FETCH NEXT FROM con INTO @old;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @new = LEFT(@old, 124) + N'_bak';
        SET @obj = N'dbo.' + QUOTENAME(@old);
        EXEC sys.sp_rename @objname = @obj, @newname = @new, @objtype = N'OBJECT';
        FETCH NEXT FROM con INTO @old;
    END
    CLOSE con;
    DEALLOCATE con;
    DECLARE ix CURSOR LOCAL FAST_FORWARD FOR
        SELECT name FROM sys.indexes
        WHERE object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@bak)) AND is_primary_key = 0
          AND is_unique_constraint = 0 AND name IS NOT NULL;
    OPEN ix;
    FETCH NEXT FROM ix INTO @old;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @new = LEFT(@old, 124) + N'_bak';
        SET @obj = N'dbo.' + QUOTENAME(@bak) + N'.' + QUOTENAME(@old);
        EXEC sys.sp_rename @objname = @obj, @newname = @new, @objtype = N'INDEX';
        FETCH NEXT FROM ix INTO @old;
    END
    CLOSE ix;
    DEALLOCATE ix;
END
GO

BEGIN TRANSACTION;

-- ---------------------------------------------------------------------------
-- vendorBill
-- ---------------------------------------------------------------------------
EXEC #rebuild N'tb_Netsuite_VendorBill';
CREATE TABLE dbo.tb_Netsuite_VendorBill (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                                nvarchar(50) NULL,
    BPA_Direction                             nvarchar(50) NULL,
    BPA_Company                               nvarchar(50) NULL,
    BPA_EntryID                               uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_VendorBill_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                              uniqueidentifier NULL,
    BPA_Status                                int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Status DEFAULT ((0)),
    BPA_Reference                             nvarchar(50) NULL,
    BPA_Reference_Description                 nvarchar(100) NULL,
    BPA_Reference2                            nvarchar(50) NULL,
    BPA_Reference2_Description                nvarchar(100) NULL,
    BPA_Action                                nvarchar(1) NULL,
    BPA_ReturnedID                            nvarchar(50) NULL,
    BPA_Syscreated                            datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified                           datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator                            nvarchar(50) NULL,
    BPA_Error                                 nvarchar(max) NULL,
    BPA_Error_Extended                        nvarchar(max) NULL,
    BPA_Description                           nvarchar(255) NULL,
    BPA_Failcount                             int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid                          uniqueidentifier NULL,
    BPA_TaskInstanceID                        int NULL,
    BPA_TaskID                                int NULL,

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    id                                        nvarchar(100) NOT NULL,
    externalId                                nvarchar(100) NULL,
    tranId                                    nvarchar(255) NULL,         -- vendor's invoice number (Reference No.)
    transactionNumber                         nvarchar(50) NULL,          -- NetSuite's own number (VENDBILL37)
    tranDate                                  date NULL,
    dueDate                                   date NULL,
    createdDate                               datetime2(0) NULL,          -- UTC
    lastModifiedDate                          datetime2(0) NULL,          -- UTC
    entityId                                  nvarchar(100) NULL,         -- vendor
    entityRefName                             nvarchar(400) NULL,
    subsidiaryId                              nvarchar(100) NULL,
    subsidiaryRefName                         nvarchar(400) NULL,
    currencyId                                nvarchar(100) NULL,
    currencyRefName                           nvarchar(100) NULL,
    accountId                                 nvarchar(100) NULL,         -- A/P account
    accountRefName                            nvarchar(400) NULL,
    postingPeriodId                           nvarchar(100) NULL,
    postingPeriodRefName                      nvarchar(100) NULL,
    termsId                                   nvarchar(100) NULL,
    termsRefName                              nvarchar(100) NULL,
    approvalStatusId                          nvarchar(100) NULL,
    approvalStatusRefName                     nvarchar(100) NULL,
    statusId                                  nvarchar(100) NULL,         -- open / Open, paidInFull / Paid In Full, ...
    statusRefName                             nvarchar(100) NULL,
    departmentId                              nvarchar(100) NULL,
    departmentRefName                         nvarchar(400) NULL,
    classId                                   nvarchar(100) NULL,
    classRefName                              nvarchar(400) NULL,
    locationId                                nvarchar(100) NULL,
    locationRefName                           nvarchar(400) NULL,
    exchangeRate                              decimal(28,10) NULL,
    total                                     decimal(19,4) NULL,
    userTotal                                 decimal(19,4) NULL,
    taxTotal                                  decimal(19,4) NULL,
    discountAmount                            decimal(19,4) NULL,
    discountDate                              date NULL,
    memo                                      nvarchar(4000) NULL,
    paymentHold                               bit NULL,
    received                                  bit NULL,
    toBePrinted                               bit NULL,
    vatRegNum                                 nvarchar(100) NULL,
    billAddressee                             nvarchar(255) NULL,
    billAttention                             nvarchar(255) NULL,
    billAddr1                                 nvarchar(255) NULL,
    billAddr2                                 nvarchar(255) NULL,
    billAddr3                                 nvarchar(255) NULL,
    billCity                                  nvarchar(100) NULL,
    billState                                 nvarchar(100) NULL,
    billZip                                   nvarchar(50) NULL,
    billCountryId                             nvarchar(10) NULL,
    billCountryRefName                        nvarchar(100) NULL,
    billAddress                               nvarchar(1000) NULL,        -- full address as text
    cseg_bit_4weeksId                         nvarchar(100) NULL,         -- custom segment
    cseg_bit_4weeksRefName                    nvarchar(400) NULL,
    custbody_document_date                    date NULL,
    custbody_establishment_code               nvarchar(100) NULL,
    custbody_15529_vendor_entity_bankId       nvarchar(100) NULL,         -- vendor bank details used for payment
    custbody_15529_vendor_entity_bankRefName  nvarchar(400) NULL,
    custbody_11187_pref_entity_bankId         nvarchar(100) NULL,
    custbody_11187_pref_entity_bankRefName    nvarchar(400) NULL,
    custbody_9997_is_for_ep_eft               bit NULL,
    custbody_11724_pay_bank_fees              bit NULL,
    custbody_stc_amount_after_discount        decimal(19,4) NULL,
    custbody_stc_tax_after_discount           decimal(19,4) NULL,
    custbody_stc_total_after_discount         decimal(19,4) NULL,
    custbody_stc_discountpercent              decimal(9,4) NULL,
    custbody_stc_daysuntilexpiry              int NULL,
    custbody_stc_payment_transaction_id       nvarchar(100) NULL,
    CONSTRAINT PK_tb_Netsuite_VendorBill PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_id ON dbo.tb_Netsuite_VendorBill (id) INCLUDE (lastModifiedDate);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_BPA_Status ON dbo.tb_Netsuite_VendorBill (BPA_Status, BPA_Direction) INCLUDE (id, BPA_Company);
PRINT N'Created  dbo.tb_Netsuite_VendorBill';

-- vendorBill/expense/items -> dbo.tb_Netsuite_VendorBill_Expense: one row per line
EXEC #rebuild N'tb_Netsuite_VendorBill_Expense';
CREATE TABLE dbo.tb_Netsuite_VendorBill_Expense (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                  nvarchar(50) NULL,
    BPA_Direction               nvarchar(50) NULL,
    BPA_Company                 nvarchar(50) NULL,
    BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                uniqueidentifier NULL,
    BPA_Status                  int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Status DEFAULT ((0)),
    BPA_Reference               nvarchar(50) NULL,
    BPA_Reference_Description   nvarchar(100) NULL,
    BPA_Reference2              nvarchar(50) NULL,
    BPA_Reference2_Description  nvarchar(100) NULL,
    BPA_Action                  nvarchar(1) NULL,
    BPA_ReturnedID              nvarchar(50) NULL,
    BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator              nvarchar(50) NULL,
    BPA_Error                   nvarchar(max) NULL,
    BPA_Error_Extended          nvarchar(max) NULL,
    BPA_Description             nvarchar(255) NULL,
    BPA_Failcount               int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Expense_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid            uniqueidentifier NULL,
    BPA_TaskInstanceID          int NULL,
    BPA_TaskID                  int NULL,

    -- Parent: BPA_ParentID = tb_Netsuite_VendorBill.BPA_EntryID
    vendorBillId                nvarchar(100) NOT NULL,     -- vendorBill/id (the parent's NetSuite id)

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    line                        int NOT NULL,
    accountId                   nvarchar(100) NULL,
    accountRefName              nvarchar(400) NULL,
    amount                      decimal(19,4) NULL,         -- net
    taxCodeId                   nvarchar(100) NULL,
    taxCodeRefName              nvarchar(100) NULL,
    taxRate1                    decimal(9,4) NULL,          -- 1.0% -> 1.0000
    tax1Amt                     decimal(19,4) NULL,
    grossAmt                    decimal(19,4) NULL,
    memo                        nvarchar(4000) NULL,
    departmentId                nvarchar(100) NULL,
    departmentRefName           nvarchar(400) NULL,
    classId                     nvarchar(100) NULL,
    classRefName                nvarchar(400) NULL,
    locationId                  nvarchar(100) NULL,
    locationRefName             nvarchar(400) NULL,
    customerId                  nvarchar(100) NULL,
    customerRefName             nvarchar(400) NULL,
    isBillable                  bit NULL,
    categoryId                  nvarchar(100) NULL,
    categoryRefName             nvarchar(400) NULL,
    amortizationSchedId         nvarchar(100) NULL,
    amortizationSchedRefName    nvarchar(400) NULL,
    amortizStartDate            date NULL,
    amortizationEndDate         date NULL,
    amortizationResidual        nvarchar(100) NULL,
    orderDoc                    nvarchar(100) NULL,         -- linked purchase order
    orderLine                   nvarchar(50) NULL,
    CONSTRAINT PK_tb_Netsuite_VendorBill_Expense PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Expense_BPA_ParentID ON dbo.tb_Netsuite_VendorBill_Expense (BPA_ParentID);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Expense_vendorBillId ON dbo.tb_Netsuite_VendorBill_Expense (vendorBillId, line);
PRINT N'Created  dbo.tb_Netsuite_VendorBill_Expense';

-- vendorBill/item/items -> dbo.tb_Netsuite_VendorBill_Item: one row per line
EXEC #rebuild N'tb_Netsuite_VendorBill_Item';
CREATE TABLE dbo.tb_Netsuite_VendorBill_Item (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                  nvarchar(50) NULL,
    BPA_Direction               nvarchar(50) NULL,
    BPA_Company                 nvarchar(50) NULL,
    BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                uniqueidentifier NULL,
    BPA_Status                  int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Status DEFAULT ((0)),
    BPA_Reference               nvarchar(50) NULL,
    BPA_Reference_Description   nvarchar(100) NULL,
    BPA_Reference2              nvarchar(50) NULL,
    BPA_Reference2_Description  nvarchar(100) NULL,
    BPA_Action                  nvarchar(1) NULL,
    BPA_ReturnedID              nvarchar(50) NULL,
    BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator              nvarchar(50) NULL,
    BPA_Error                   nvarchar(max) NULL,
    BPA_Error_Extended          nvarchar(max) NULL,
    BPA_Description             nvarchar(255) NULL,
    BPA_Failcount               int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_Item_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid            uniqueidentifier NULL,
    BPA_TaskInstanceID          int NULL,
    BPA_TaskID                  int NULL,

    -- Parent: BPA_ParentID = tb_Netsuite_VendorBill.BPA_EntryID
    vendorBillId                nvarchar(100) NOT NULL,     -- vendorBill/id (the parent's NetSuite id)

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    line                        int NOT NULL,
    uniqueKey                   int NULL,                   -- line unique key
    itemId                      nvarchar(100) NULL,
    itemRefName                 nvarchar(400) NULL,
    vendorName                  nvarchar(255) NULL,         -- vendor's item code
    description                 nvarchar(4000) NULL,
    quantity                    decimal(28,10) NULL,
    units                       nvarchar(100) NULL,
    rate                        decimal(28,10) NULL,
    amount                      decimal(19,4) NULL,         -- net
    taxCodeId                   nvarchar(100) NULL,
    taxCodeRefName              nvarchar(100) NULL,
    taxRate1                    decimal(9,4) NULL,
    tax1Amt                     decimal(19,4) NULL,
    grossAmt                    decimal(19,4) NULL,
    departmentId                nvarchar(100) NULL,
    departmentRefName           nvarchar(400) NULL,
    classId                     nvarchar(100) NULL,
    classRefName                nvarchar(400) NULL,
    customerId                  nvarchar(100) NULL,
    customerRefName             nvarchar(400) NULL,
    isBillable                  bit NULL,
    orderLine                   int NULL,                   -- linked purchase order line
    amortizStartDate            date NULL,
    amortizationEndDate         date NULL,
    amortizationResidual        nvarchar(100) NULL,
    CONSTRAINT PK_tb_Netsuite_VendorBill_Item PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Item_BPA_ParentID ON dbo.tb_Netsuite_VendorBill_Item (BPA_ParentID);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_Item_vendorBillId ON dbo.tb_Netsuite_VendorBill_Item (vendorBillId, line);
PRINT N'Created  dbo.tb_Netsuite_VendorBill_Item';

-- vendorBill/glImpactChanges/items -> dbo.tb_Netsuite_VendorBill_GLImpactChanges: one row per line
EXEC #rebuild N'tb_Netsuite_VendorBill_GLImpactChanges';
CREATE TABLE dbo.tb_Netsuite_VendorBill_GLImpactChanges (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                  nvarchar(50) NULL,
    BPA_Direction               nvarchar(50) NULL,
    BPA_Company                 nvarchar(50) NULL,
    BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_VendorBill_GLImpactChanges_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                uniqueidentifier NULL,
    BPA_Status                  int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_GLImpactChanges_Status DEFAULT ((0)),
    BPA_Reference               nvarchar(50) NULL,
    BPA_Reference_Description   nvarchar(100) NULL,
    BPA_Reference2              nvarchar(50) NULL,
    BPA_Reference2_Description  nvarchar(100) NULL,
    BPA_Action                  nvarchar(1) NULL,
    BPA_ReturnedID              nvarchar(50) NULL,
    BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_GLImpactChanges_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_Netsuite_VendorBill_GLImpactChanges_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator              nvarchar(50) NULL,
    BPA_Error                   nvarchar(max) NULL,
    BPA_Error_Extended          nvarchar(max) NULL,
    BPA_Description             nvarchar(255) NULL,
    BPA_Failcount               int NULL CONSTRAINT DF_tb_Netsuite_VendorBill_GLImpactChanges_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid            uniqueidentifier NULL,
    BPA_TaskInstanceID          int NULL,
    BPA_TaskID                  int NULL,

    -- Parent: BPA_ParentID = tb_Netsuite_VendorBill.BPA_EntryID
    vendorBillId                nvarchar(100) NOT NULL,     -- vendorBill/id (the parent's NetSuite id)

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    creationDate                datetime2(0) NULL,          -- when the GL impact was changed
    transactionDate             date NULL,
    transactionType             nvarchar(100) NULL,
    transactionKey              nvarchar(100) NULL,
    transactionNumber           nvarchar(100) NULL,
    transactionUrl              nvarchar(1000) NULL,
    changedById                 nvarchar(100) NULL,         -- employee
    changedByRefName            nvarchar(400) NULL,
    CONSTRAINT PK_tb_Netsuite_VendorBill_GLImpactChanges PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_GLImpactChanges_BPA_ParentID ON dbo.tb_Netsuite_VendorBill_GLImpactChanges (BPA_ParentID);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_VendorBill_GLImpactChanges_vendorBillId ON dbo.tb_Netsuite_VendorBill_GLImpactChanges (vendorBillId, transactionKey);
PRINT N'Created  dbo.tb_Netsuite_VendorBill_GLImpactChanges';

COMMIT TRANSACTION;
GO
DROP PROCEDURE #rebuild;
GO
