/*
    Foundation Group - staging tables for NetSuite master data (FROM tasks,
    NetSuite connector): every table, header and child. Compare your own
    tables with it: tools/netsuite_masterdata.py check-ddl.

    dbo.tb_NetSuite_Vendor                    vendor
    dbo.tb_NetSuite_Vendor_AddressBook        vendor/addressBook/items
    dbo.tb_NetSuite_Classification            classification
    dbo.tb_NetSuite_Classification_Subsidiary classification/subsidiary/items
    dbo.tb_NetSuite_Department                department
    dbo.tb_NetSuite_Department_Subsidiary     department/subsidiary/items
    dbo.tb_NetSuite_Location                  location
    dbo.tb_NetSuite_Location_Subsidiary       location/subsidiary/items
    dbo.tb_NetSuite_Currency                  currency
    dbo.tb_NetSuite_Term                      term
    dbo.tb_Netsuite_SalesTaxItem              salesTaxItem
    dbo.tb_NetSuite_Account                   account
    dbo.tb_NetSuite_Account_Subsidiary        account/subsidiary/items
    dbo.tb_NetSuite_Subsidiary                subsidiary

    Column names are the NetSuite REST field names. A reference field is stored
    as <field>Id + <field>RefName (the values on the record itself; the
    connector does not need to expand the referenced record). Timestamps
    (lastModifiedDate, dateCreated) come as 'YYYY-MM-DDThh:mm:ssZ' and are UTC.
    A child row links to its parent through BPA_ParentID = parent BPA_EntryID,
    and holds the parent's NetSuite id in <record>Id.

    Existing tables are renamed to <table>_bak (constraints and indexes included)
    before the new ones are created; drop the _bak tables once loading works.
    Stops without changes if a _bak table already exists.
    Runs in a single transaction.

    Generated by tools/netsuite_masterdata.py: change the spec there and
    regenerate. See docs/foundation_masterdata.md and the validation report
    docs/foundation_masterdata_validation.md.
*/
SET XACT_ABORT ON;
SET NOCOUNT ON;
IF OBJECT_ID(N'tempdb..#rebuild') IS NOT NULL DROP PROCEDURE #rebuild;
GO
-- Renames an existing table to <table>_bak (constraints and indexes get a _bak
-- suffix too), so the new definition can be created without losing data.
CREATE PROCEDURE #rebuild @table sysname AS
BEGIN
    DECLARE @bak sysname = @table + N'_bak', @old sysname, @new sysname, @obj nvarchar(300), @msg nvarchar(400);
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@table), N'U') IS NULL RETURN;
    IF OBJECT_ID(N'dbo.' + QUOTENAME(@bak), N'U') IS NOT NULL
    BEGIN
        SET @msg = N'dbo.' + @bak + N' already exists; drop or rename it first.';
        THROW 50001, @msg, 1;
    END
    SET @obj = N'dbo.' + QUOTENAME(@table);
    EXEC sys.sp_rename @objname = @obj, @newname = @bak, @objtype = N'OBJECT';
    PRINT N'Renamed  dbo.' + @table + N' -> ' + @bak;
    DECLARE con CURSOR LOCAL FAST_FORWARD FOR
        SELECT name FROM sys.objects
        WHERE parent_object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@bak)) AND type IN ('PK', 'UQ', 'D', 'C', 'F');
    OPEN con;
    FETCH NEXT FROM con INTO @old;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @new = LEFT(@old, 124) + N'_bak';
        SET @obj = N'dbo.' + QUOTENAME(@old);
        EXEC sys.sp_rename @objname = @obj, @newname = @new, @objtype = N'OBJECT';
        FETCH NEXT FROM con INTO @old;
    END
    CLOSE con;
    DEALLOCATE con;
    DECLARE ix CURSOR LOCAL FAST_FORWARD FOR
        SELECT name FROM sys.indexes
        WHERE object_id = OBJECT_ID(N'dbo.' + QUOTENAME(@bak)) AND is_primary_key = 0
          AND is_unique_constraint = 0 AND name IS NOT NULL;
    OPEN ix;
    FETCH NEXT FROM ix INTO @old;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SET @new = LEFT(@old, 124) + N'_bak';
        SET @obj = N'dbo.' + QUOTENAME(@bak) + N'.' + QUOTENAME(@old);
        EXEC sys.sp_rename @objname = @obj, @newname = @new, @objtype = N'INDEX';
        FETCH NEXT FROM ix INTO @old;
    END
    CLOSE ix;
    DEALLOCATE ix;
END
GO

BEGIN TRANSACTION;

-- ---------------------------------------------------------------------------
-- vendor
-- ---------------------------------------------------------------------------
EXEC #rebuild N'tb_NetSuite_Vendor';
CREATE TABLE dbo.tb_NetSuite_Vendor (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                           nvarchar(50) NULL,
    BPA_Direction                        nvarchar(50) NULL,
    BPA_Company                          nvarchar(50) NULL,
    BPA_EntryID                          uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Vendor_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                         uniqueidentifier NULL,
    BPA_Status                           int NULL CONSTRAINT DF_tb_NetSuite_Vendor_Status DEFAULT ((0)),
    BPA_Reference                        nvarchar(50) NULL,
    BPA_Reference_Description            nvarchar(100) NULL,
    BPA_Reference2                       nvarchar(50) NULL,
    BPA_Reference2_Description           nvarchar(100) NULL,
    BPA_Action                           nvarchar(1) NULL,
    BPA_ReturnedID                       nvarchar(50) NULL,
    BPA_Syscreated                       datetime NULL CONSTRAINT DF_tb_NetSuite_Vendor_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified                      datetime NULL CONSTRAINT DF_tb_NetSuite_Vendor_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator                       nvarchar(50) NULL,
    BPA_Error                            nvarchar(max) NULL,
    BPA_Error_Extended                   nvarchar(max) NULL,
    BPA_Description                      nvarchar(255) NULL,
    BPA_Failcount                        int NULL CONSTRAINT DF_tb_NetSuite_Vendor_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid                     uniqueidentifier NULL,
    BPA_TaskInstanceID                   int NULL,
    BPA_TaskID                           int NULL,

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    id                                   nvarchar(100) NOT NULL,
    externalId                           nvarchar(100) NULL,
    entityId                             nvarchar(255) NULL,         -- vendor number / name in lists
    companyName                          nvarchar(255) NULL,
    legalName                            nvarchar(255) NULL,
    isPerson                             bit NULL,                   -- BOD isindividual: Company / Individual
    salutation                           nvarchar(50) NULL,
    firstName                            nvarchar(100) NULL,
    middleName                           nvarchar(100) NULL,
    lastName                             nvarchar(100) NULL,
    title                                nvarchar(100) NULL,
    printOnCheckAs                       nvarchar(255) NULL,
    email                                nvarchar(255) NULL,
    altEmail                             nvarchar(255) NULL,
    phone                                nvarchar(50) NULL,
    altPhone                             nvarchar(50) NULL,
    mobilePhone                          nvarchar(50) NULL,
    homePhone                            nvarchar(50) NULL,
    fax                                  nvarchar(50) NULL,
    url                                  nvarchar(400) NULL,
    comments                             nvarchar(4000) NULL,
    defaultAddress                       nvarchar(1000) NULL,        -- default billing address as text
    accountNumber                        nvarchar(100) NULL,         -- our account number at the vendor
    vatRegNumber                         nvarchar(50) NULL,
    taxIdNum                             nvarchar(50) NULL,
    creditLimit                          decimal(19,4) NULL,
    balance                              decimal(19,4) NULL,         -- snapshot at load time
    balancePrimary                       decimal(19,4) NULL,         -- snapshot at load time, primary currency
    is1099Eligible                       bit NULL,
    isJobResourceVend                    bit NULL,
    isAutogeneratedRepresentingEntity    bit NULL,                   -- intercompany vendor created for a subsidiary
    isInactive                           bit NULL,
    emailTransactions                    bit NULL,
    printTransactions                    bit NULL,
    faxTransactions                      bit NULL,
    subsidiaryEdition                    nvarchar(10) NULL,          -- UK, NL, ...
    dateCreated                          datetime2(0) NULL,          -- UTC
    lastModifiedDate                     datetime2(0) NULL,          -- UTC
    subsidiaryId                         nvarchar(100) NULL,         -- primary subsidiary
    subsidiaryRefName                    nvarchar(400) NULL,
    representingSubsidiaryId             nvarchar(100) NULL,
    representingSubsidiaryRefName        nvarchar(400) NULL,
    categoryId                           nvarchar(100) NULL,
    categoryRefName                      nvarchar(400) NULL,
    currencyId                           nvarchar(100) NULL,         -- primary currency
    currencyRefName                      nvarchar(400) NULL,
    termsId                              nvarchar(100) NULL,
    termsRefName                         nvarchar(400) NULL,
    expenseAccountId                     nvarchar(100) NULL,         -- default expense account
    expenseAccountRefName                nvarchar(400) NULL,
    payablesAccountId                    nvarchar(100) NULL,         -- default A/P account
    payablesAccountRefName               nvarchar(400) NULL,
    defaultVendorPaymentAccountId        nvarchar(100) NULL,
    defaultVendorPaymentAccountRefName   nvarchar(400) NULL,
    taxItemId                            nvarchar(100) NULL,         -- default tax code
    taxItemRefName                       nvarchar(400) NULL,
    emailPreferenceId                    nvarchar(50) NULL,
    emailPreferenceRefName               nvarchar(100) NULL,
    custentity_2663_payment_method       bit NULL,                   -- Electronic Bank Payments: pays by EFT
    custentity_11724_pay_bank_fees       bit NULL,
    custentity_2663_email_address_notif  nvarchar(400) NULL,         -- EFT notification e-mail
    custentity_tax_reg_no                nvarchar(100) NULL,
    CONSTRAINT PK_tb_NetSuite_Vendor PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Vendor_id ON dbo.tb_NetSuite_Vendor (id) INCLUDE (lastModifiedDate);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Vendor_BPA_Status ON dbo.tb_NetSuite_Vendor (BPA_Status, BPA_Direction) INCLUDE (id, BPA_Company);
PRINT N'Created  dbo.tb_NetSuite_Vendor';

-- vendor/addressBook/items -> dbo.tb_NetSuite_Vendor_AddressBook: one row per line
EXEC #rebuild N'tb_NetSuite_Vendor_AddressBook';
CREATE TABLE dbo.tb_NetSuite_Vendor_AddressBook (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                  nvarchar(50) NULL,
    BPA_Direction               nvarchar(50) NULL,
    BPA_Company                 nvarchar(50) NULL,
    BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Vendor_AddressBook_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                uniqueidentifier NULL,
    BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Vendor_AddressBook_Status DEFAULT ((0)),
    BPA_Reference               nvarchar(50) NULL,
    BPA_Reference_Description   nvarchar(100) NULL,
    BPA_Reference2              nvarchar(50) NULL,
    BPA_Reference2_Description  nvarchar(100) NULL,
    BPA_Action                  nvarchar(1) NULL,
    BPA_ReturnedID              nvarchar(50) NULL,
    BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Vendor_AddressBook_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Vendor_AddressBook_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator              nvarchar(50) NULL,
    BPA_Error                   nvarchar(max) NULL,
    BPA_Error_Extended          nvarchar(max) NULL,
    BPA_Description             nvarchar(255) NULL,
    BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Vendor_AddressBook_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid            uniqueidentifier NULL,
    BPA_TaskInstanceID          int NULL,
    BPA_TaskID                  int NULL,

    -- Parent: BPA_ParentID = tb_NetSuite_Vendor.BPA_EntryID
    vendorId                    nvarchar(100) NOT NULL,     -- vendor/id (the parent's NetSuite id)

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    addressBookId               int NOT NULL,               -- address book line id
    label                       nvarchar(255) NULL,
    defaultBilling              bit NULL,
    defaultShipping             bit NULL,
    addressBookAddress_text     nvarchar(1000) NULL,        -- full address as text
    addressee                   nvarchar(255) NULL,
    attention                   nvarchar(255) NULL,
    addr1                       nvarchar(255) NULL,
    addr2                       nvarchar(255) NULL,
    addr3                       nvarchar(255) NULL,
    city                        nvarchar(100) NULL,
    state                       nvarchar(100) NULL,
    zip                         nvarchar(50) NULL,
    countryId                   nvarchar(10) NULL,          -- GB, NL, BE, ...
    countryRefName              nvarchar(100) NULL,
    addrPhone                   nvarchar(50) NULL,
    override                    bit NULL,
    CONSTRAINT PK_tb_NetSuite_Vendor_AddressBook PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Vendor_AddressBook_BPA_ParentID ON dbo.tb_NetSuite_Vendor_AddressBook (BPA_ParentID);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Vendor_AddressBook_vendorId ON dbo.tb_NetSuite_Vendor_AddressBook (vendorId, addressBookId);
PRINT N'Created  dbo.tb_NetSuite_Vendor_AddressBook';

-- ---------------------------------------------------------------------------
-- classification
-- ---------------------------------------------------------------------------
EXEC #rebuild N'tb_NetSuite_Classification';
CREATE TABLE dbo.tb_NetSuite_Classification (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                  nvarchar(50) NULL,
    BPA_Direction               nvarchar(50) NULL,
    BPA_Company                 nvarchar(50) NULL,
    BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Classification_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                uniqueidentifier NULL,
    BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Classification_Status DEFAULT ((0)),
    BPA_Reference               nvarchar(50) NULL,
    BPA_Reference_Description   nvarchar(100) NULL,
    BPA_Reference2              nvarchar(50) NULL,
    BPA_Reference2_Description  nvarchar(100) NULL,
    BPA_Action                  nvarchar(1) NULL,
    BPA_ReturnedID              nvarchar(50) NULL,
    BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Classification_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Classification_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator              nvarchar(50) NULL,
    BPA_Error                   nvarchar(max) NULL,
    BPA_Error_Extended          nvarchar(max) NULL,
    BPA_Description             nvarchar(255) NULL,
    BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Classification_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid            uniqueidentifier NULL,
    BPA_TaskInstanceID          int NULL,
    BPA_TaskID                  int NULL,

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    id                          nvarchar(100) NOT NULL,
    externalId                  nvarchar(100) NULL,
    name                        nvarchar(255) NULL,
    fullName                    nvarchar(1000) NULL,        -- Parent : Child
    parentId                    nvarchar(100) NULL,
    parentRefName               nvarchar(400) NULL,
    includeChildren             bit NULL,                   -- also valid for child subsidiaries
    isInactive                  bit NULL,
    lastModifiedDate            datetime2(0) NULL,          -- UTC
    CONSTRAINT PK_tb_NetSuite_Classification PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Classification_id ON dbo.tb_NetSuite_Classification (id) INCLUDE (lastModifiedDate);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Classification_BPA_Status ON dbo.tb_NetSuite_Classification (BPA_Status, BPA_Direction) INCLUDE (id, BPA_Company);
PRINT N'Created  dbo.tb_NetSuite_Classification';

-- classification/subsidiary/items -> dbo.tb_NetSuite_Classification_Subsidiary: one row per selected subsidiary
EXEC #rebuild N'tb_NetSuite_Classification_Subsidiary';
CREATE TABLE dbo.tb_NetSuite_Classification_Subsidiary (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                  nvarchar(50) NULL,
    BPA_Direction               nvarchar(50) NULL,
    BPA_Company                 nvarchar(50) NULL,
    BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Classification_Subsidiary_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                uniqueidentifier NULL,
    BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Classification_Subsidiary_Status DEFAULT ((0)),
    BPA_Reference               nvarchar(50) NULL,
    BPA_Reference_Description   nvarchar(100) NULL,
    BPA_Reference2              nvarchar(50) NULL,
    BPA_Reference2_Description  nvarchar(100) NULL,
    BPA_Action                  nvarchar(1) NULL,
    BPA_ReturnedID              nvarchar(50) NULL,
    BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Classification_Subsidiary_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Classification_Subsidiary_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator              nvarchar(50) NULL,
    BPA_Error                   nvarchar(max) NULL,
    BPA_Error_Extended          nvarchar(max) NULL,
    BPA_Description             nvarchar(255) NULL,
    BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Classification_Subsidiary_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid            uniqueidentifier NULL,
    BPA_TaskInstanceID          int NULL,
    BPA_TaskID                  int NULL,

    -- Parent: BPA_ParentID = tb_NetSuite_Classification.BPA_EntryID
    classificationId            nvarchar(100) NOT NULL,     -- classification/id (the parent's NetSuite id)

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    subsidiaryId                nvarchar(100) NULL,
    subsidiaryRefName           nvarchar(400) NULL,
    CONSTRAINT PK_tb_NetSuite_Classification_Subsidiary PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Classification_Subsidiary_BPA_ParentID ON dbo.tb_NetSuite_Classification_Subsidiary (BPA_ParentID);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Classification_Subsidiary_classificationId ON dbo.tb_NetSuite_Classification_Subsidiary (classificationId, subsidiaryId);
PRINT N'Created  dbo.tb_NetSuite_Classification_Subsidiary';

-- ---------------------------------------------------------------------------
-- department
-- ---------------------------------------------------------------------------
EXEC #rebuild N'tb_NetSuite_Department';
CREATE TABLE dbo.tb_NetSuite_Department (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                  nvarchar(50) NULL,
    BPA_Direction               nvarchar(50) NULL,
    BPA_Company                 nvarchar(50) NULL,
    BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Department_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                uniqueidentifier NULL,
    BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Department_Status DEFAULT ((0)),
    BPA_Reference               nvarchar(50) NULL,
    BPA_Reference_Description   nvarchar(100) NULL,
    BPA_Reference2              nvarchar(50) NULL,
    BPA_Reference2_Description  nvarchar(100) NULL,
    BPA_Action                  nvarchar(1) NULL,
    BPA_ReturnedID              nvarchar(50) NULL,
    BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Department_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Department_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator              nvarchar(50) NULL,
    BPA_Error                   nvarchar(max) NULL,
    BPA_Error_Extended          nvarchar(max) NULL,
    BPA_Description             nvarchar(255) NULL,
    BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Department_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid            uniqueidentifier NULL,
    BPA_TaskInstanceID          int NULL,
    BPA_TaskID                  int NULL,

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    id                          nvarchar(100) NOT NULL,
    externalId                  nvarchar(100) NULL,
    name                        nvarchar(255) NULL,
    fullName                    nvarchar(1000) NULL,        -- Parent : Child
    parentId                    nvarchar(100) NULL,
    parentRefName               nvarchar(400) NULL,
    includeChildren             bit NULL,                   -- also valid for child subsidiaries
    isInactive                  bit NULL,
    lastModifiedDate            datetime2(0) NULL,          -- UTC
    CONSTRAINT PK_tb_NetSuite_Department PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Department_id ON dbo.tb_NetSuite_Department (id) INCLUDE (lastModifiedDate);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Department_BPA_Status ON dbo.tb_NetSuite_Department (BPA_Status, BPA_Direction) INCLUDE (id, BPA_Company);
PRINT N'Created  dbo.tb_NetSuite_Department';

-- department/subsidiary/items -> dbo.tb_NetSuite_Department_Subsidiary: one row per selected subsidiary
EXEC #rebuild N'tb_NetSuite_Department_Subsidiary';
CREATE TABLE dbo.tb_NetSuite_Department_Subsidiary (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                  nvarchar(50) NULL,
    BPA_Direction               nvarchar(50) NULL,
    BPA_Company                 nvarchar(50) NULL,
    BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Department_Subsidiary_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                uniqueidentifier NULL,
    BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Department_Subsidiary_Status DEFAULT ((0)),
    BPA_Reference               nvarchar(50) NULL,
    BPA_Reference_Description   nvarchar(100) NULL,
    BPA_Reference2              nvarchar(50) NULL,
    BPA_Reference2_Description  nvarchar(100) NULL,
    BPA_Action                  nvarchar(1) NULL,
    BPA_ReturnedID              nvarchar(50) NULL,
    BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Department_Subsidiary_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Department_Subsidiary_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator              nvarchar(50) NULL,
    BPA_Error                   nvarchar(max) NULL,
    BPA_Error_Extended          nvarchar(max) NULL,
    BPA_Description             nvarchar(255) NULL,
    BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Department_Subsidiary_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid            uniqueidentifier NULL,
    BPA_TaskInstanceID          int NULL,
    BPA_TaskID                  int NULL,

    -- Parent: BPA_ParentID = tb_NetSuite_Department.BPA_EntryID
    departmentId                nvarchar(100) NOT NULL,     -- department/id (the parent's NetSuite id)

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    subsidiaryId                nvarchar(100) NULL,
    subsidiaryRefName           nvarchar(400) NULL,
    CONSTRAINT PK_tb_NetSuite_Department_Subsidiary PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Department_Subsidiary_BPA_ParentID ON dbo.tb_NetSuite_Department_Subsidiary (BPA_ParentID);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Department_Subsidiary_departmentId ON dbo.tb_NetSuite_Department_Subsidiary (departmentId, subsidiaryId);
PRINT N'Created  dbo.tb_NetSuite_Department_Subsidiary';

-- ---------------------------------------------------------------------------
-- location
-- ---------------------------------------------------------------------------
EXEC #rebuild N'tb_NetSuite_Location';
CREATE TABLE dbo.tb_NetSuite_Location (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                  nvarchar(50) NULL,
    BPA_Direction               nvarchar(50) NULL,
    BPA_Company                 nvarchar(50) NULL,
    BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Location_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                uniqueidentifier NULL,
    BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Location_Status DEFAULT ((0)),
    BPA_Reference               nvarchar(50) NULL,
    BPA_Reference_Description   nvarchar(100) NULL,
    BPA_Reference2              nvarchar(50) NULL,
    BPA_Reference2_Description  nvarchar(100) NULL,
    BPA_Action                  nvarchar(1) NULL,
    BPA_ReturnedID              nvarchar(50) NULL,
    BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Location_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Location_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator              nvarchar(50) NULL,
    BPA_Error                   nvarchar(max) NULL,
    BPA_Error_Extended          nvarchar(max) NULL,
    BPA_Description             nvarchar(255) NULL,
    BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Location_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid            uniqueidentifier NULL,
    BPA_TaskInstanceID          int NULL,
    BPA_TaskID                  int NULL,

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    id                          nvarchar(100) NOT NULL,
    externalId                  nvarchar(100) NULL,
    name                        nvarchar(255) NULL,
    fullName                    nvarchar(1000) NULL,        -- Parent : Child
    parentId                    nvarchar(100) NULL,
    parentRefName               nvarchar(400) NULL,
    locationTypeId              nvarchar(50) NULL,
    locationTypeRefName         nvarchar(100) NULL,
    makeInventoryAvailable      bit NULL,
    timeZoneId                  nvarchar(100) NULL,
    timeZoneRefName             nvarchar(200) NULL,
    tranPrefix                  nvarchar(50) NULL,
    latitude                    decimal(12,8) NULL,
    longitude                   decimal(12,8) NULL,
    isInactive                  bit NULL,
    lastModifiedDate            datetime2(0) NULL,          -- UTC
    CONSTRAINT PK_tb_NetSuite_Location PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Location_id ON dbo.tb_NetSuite_Location (id) INCLUDE (lastModifiedDate);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Location_BPA_Status ON dbo.tb_NetSuite_Location (BPA_Status, BPA_Direction) INCLUDE (id, BPA_Company);
PRINT N'Created  dbo.tb_NetSuite_Location';

-- location/subsidiary/items -> dbo.tb_NetSuite_Location_Subsidiary: one row per selected subsidiary
EXEC #rebuild N'tb_NetSuite_Location_Subsidiary';
CREATE TABLE dbo.tb_NetSuite_Location_Subsidiary (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                  nvarchar(50) NULL,
    BPA_Direction               nvarchar(50) NULL,
    BPA_Company                 nvarchar(50) NULL,
    BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Location_Subsidiary_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                uniqueidentifier NULL,
    BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Location_Subsidiary_Status DEFAULT ((0)),
    BPA_Reference               nvarchar(50) NULL,
    BPA_Reference_Description   nvarchar(100) NULL,
    BPA_Reference2              nvarchar(50) NULL,
    BPA_Reference2_Description  nvarchar(100) NULL,
    BPA_Action                  nvarchar(1) NULL,
    BPA_ReturnedID              nvarchar(50) NULL,
    BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Location_Subsidiary_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Location_Subsidiary_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator              nvarchar(50) NULL,
    BPA_Error                   nvarchar(max) NULL,
    BPA_Error_Extended          nvarchar(max) NULL,
    BPA_Description             nvarchar(255) NULL,
    BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Location_Subsidiary_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid            uniqueidentifier NULL,
    BPA_TaskInstanceID          int NULL,
    BPA_TaskID                  int NULL,

    -- Parent: BPA_ParentID = tb_NetSuite_Location.BPA_EntryID
    locationId                  nvarchar(100) NOT NULL,     -- location/id (the parent's NetSuite id)

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    subsidiaryId                nvarchar(100) NULL,
    subsidiaryRefName           nvarchar(400) NULL,
    CONSTRAINT PK_tb_NetSuite_Location_Subsidiary PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Location_Subsidiary_BPA_ParentID ON dbo.tb_NetSuite_Location_Subsidiary (BPA_ParentID);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Location_Subsidiary_locationId ON dbo.tb_NetSuite_Location_Subsidiary (locationId, subsidiaryId);
PRINT N'Created  dbo.tb_NetSuite_Location_Subsidiary';

-- ---------------------------------------------------------------------------
-- currency
-- ---------------------------------------------------------------------------
EXEC #rebuild N'tb_NetSuite_Currency';
CREATE TABLE dbo.tb_NetSuite_Currency (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                  nvarchar(50) NULL,
    BPA_Direction               nvarchar(50) NULL,
    BPA_Company                 nvarchar(50) NULL,
    BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Currency_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                uniqueidentifier NULL,
    BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Currency_Status DEFAULT ((0)),
    BPA_Reference               nvarchar(50) NULL,
    BPA_Reference_Description   nvarchar(100) NULL,
    BPA_Reference2              nvarchar(50) NULL,
    BPA_Reference2_Description  nvarchar(100) NULL,
    BPA_Action                  nvarchar(1) NULL,
    BPA_ReturnedID              nvarchar(50) NULL,
    BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Currency_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Currency_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator              nvarchar(50) NULL,
    BPA_Error                   nvarchar(max) NULL,
    BPA_Error_Extended          nvarchar(max) NULL,
    BPA_Description             nvarchar(255) NULL,
    BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Currency_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid            uniqueidentifier NULL,
    BPA_TaskInstanceID          int NULL,
    BPA_TaskID                  int NULL,

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    id                          nvarchar(100) NOT NULL,
    externalId                  nvarchar(100) NULL,
    name                        nvarchar(100) NULL,         -- GBP, EUR, ...
    symbol                      nvarchar(10) NULL,          -- ISO code
    displaySymbol               nvarchar(10) NULL,
    isBaseCurrency              bit NULL,
    exchangeRate                decimal(28,10) NULL,        -- default rate against the base currency
    currencyPrecision           int NULL,
    includeInFxRateUpdates      bit NULL,
    overrideCurrencyFormat      bit NULL,
    symbolPlacementId           nvarchar(50) NULL,
    symbolPlacementRefName      nvarchar(100) NULL,
    localeId                    nvarchar(50) NULL,
    localeRefName               nvarchar(100) NULL,
    formatSample                nvarchar(100) NULL,
    isInactive                  bit NULL,
    lastModifiedDate            datetime2(0) NULL,          -- UTC
    CONSTRAINT PK_tb_NetSuite_Currency PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Currency_id ON dbo.tb_NetSuite_Currency (id) INCLUDE (lastModifiedDate);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Currency_BPA_Status ON dbo.tb_NetSuite_Currency (BPA_Status, BPA_Direction) INCLUDE (id, BPA_Company);
PRINT N'Created  dbo.tb_NetSuite_Currency';

-- ---------------------------------------------------------------------------
-- term
-- ---------------------------------------------------------------------------
EXEC #rebuild N'tb_NetSuite_Term';
CREATE TABLE dbo.tb_NetSuite_Term (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                  nvarchar(50) NULL,
    BPA_Direction               nvarchar(50) NULL,
    BPA_Company                 nvarchar(50) NULL,
    BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Term_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                uniqueidentifier NULL,
    BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Term_Status DEFAULT ((0)),
    BPA_Reference               nvarchar(50) NULL,
    BPA_Reference_Description   nvarchar(100) NULL,
    BPA_Reference2              nvarchar(50) NULL,
    BPA_Reference2_Description  nvarchar(100) NULL,
    BPA_Action                  nvarchar(1) NULL,
    BPA_ReturnedID              nvarchar(50) NULL,
    BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Term_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Term_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator              nvarchar(50) NULL,
    BPA_Error                   nvarchar(max) NULL,
    BPA_Error_Extended          nvarchar(max) NULL,
    BPA_Description             nvarchar(255) NULL,
    BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Term_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid            uniqueidentifier NULL,
    BPA_TaskInstanceID          int NULL,
    BPA_TaskID                  int NULL,

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    id                          nvarchar(100) NOT NULL,
    externalId                  nvarchar(100) NULL,
    name                        nvarchar(255) NULL,         -- Net 30, ...
    dateDriven                  bit NULL,                   -- 0 = standard term, 1 = date driven
    daysUntilNetDue             int NULL,                   -- standard
    discountPercent             decimal(9,4) NULL,          -- standard
    daysUntilExpiry             int NULL,                   -- standard: discount days
    dayOfMonthNetDue            int NULL,                   -- date driven
    dueNextMonthIfWithinDays    int NULL,                   -- date driven
    discountPercentDateDriven   decimal(9,4) NULL,          -- date driven
    dayDiscountExpires          int NULL,                   -- date driven
    isInactive                  bit NULL,
    CONSTRAINT PK_tb_NetSuite_Term PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Term_id ON dbo.tb_NetSuite_Term (id);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Term_BPA_Status ON dbo.tb_NetSuite_Term (BPA_Status, BPA_Direction) INCLUDE (id, BPA_Company);
PRINT N'Created  dbo.tb_NetSuite_Term';

-- ---------------------------------------------------------------------------
-- salesTaxItem
-- ---------------------------------------------------------------------------
EXEC #rebuild N'tb_Netsuite_SalesTaxItem';
CREATE TABLE dbo.tb_Netsuite_SalesTaxItem (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                             nvarchar(50) NULL,
    BPA_Direction                          nvarchar(50) NULL,
    BPA_Company                            nvarchar(50) NULL,
    BPA_EntryID                            uniqueidentifier NOT NULL CONSTRAINT DF_tb_Netsuite_SalesTaxItem_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                           uniqueidentifier NULL,
    BPA_Status                             int NULL CONSTRAINT DF_tb_Netsuite_SalesTaxItem_Status DEFAULT ((0)),
    BPA_Reference                          nvarchar(50) NULL,
    BPA_Reference_Description              nvarchar(100) NULL,
    BPA_Reference2                         nvarchar(50) NULL,
    BPA_Reference2_Description             nvarchar(100) NULL,
    BPA_Action                             nvarchar(1) NULL,
    BPA_ReturnedID                         nvarchar(50) NULL,
    BPA_Syscreated                         datetime NULL CONSTRAINT DF_tb_Netsuite_SalesTaxItem_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified                        datetime NULL CONSTRAINT DF_tb_Netsuite_SalesTaxItem_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator                         nvarchar(50) NULL,
    BPA_Error                              nvarchar(max) NULL,
    BPA_Error_Extended                     nvarchar(max) NULL,
    BPA_Description                        nvarchar(255) NULL,
    BPA_Failcount                          int NULL CONSTRAINT DF_tb_Netsuite_SalesTaxItem_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid                       uniqueidentifier NULL,
    BPA_TaskInstanceID                     int NULL,
    BPA_TaskID                             int NULL,

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    id                                     nvarchar(100) NOT NULL,
    externalId                             nvarchar(100) NULL,
    itemId                                 nvarchar(100) NULL,         -- tax code: E-BE, S-GB, ...
    description                            nvarchar(1000) NULL,
    rate                                   decimal(9,4) NULL,          -- 0.00% -> 0.0000
    effectiveFrom                          date NULL,
    validUntil                             date NULL,
    available                              nvarchar(20) NULL,          -- BOTH / SALE / PURCHASE
    exempt                                 bit NULL,
    export                                 bit NULL,
    service                                bit NULL,
    reverseCharge                          bit NULL,
    ecCode                                 bit NULL,                   -- EC (intra-EU) code
    isDefault                              bit NULL,
    excludeFromTaxReports                  bit NULL,
    includeChildren                        bit NULL,
    isInactive                             bit NULL,
    nexusCountryId                         nvarchar(10) NULL,          -- country of the tax nexus
    nexusCountryRefName                    nvarchar(100) NULL,
    subsidiaryId                           nvarchar(100) NULL,
    subsidiaryRefName                      nvarchar(400) NULL,
    parentId                               nvarchar(100) NULL,
    parentRefName                          nvarchar(400) NULL,
    taxTypeId                              nvarchar(100) NULL,
    taxTypeRefName                         nvarchar(400) NULL,
    taxAgencyId                            nvarchar(100) NULL,         -- vendor the tax is paid to
    taxAgencyRefName                       nvarchar(400) NULL,
    purchaseAccountId                      nvarchar(100) NULL,         -- BOD acct1 = name
    purchaseAccountRefName                 nvarchar(400) NULL,
    saleAccountId                          nvarchar(100) NULL,         -- BOD acct2 = name
    saleAccountRefName                     nvarchar(400) NULL,
    defaultTaxCodeId                       nvarchar(100) NULL,
    defaultTaxCodeRefName                  nvarchar(400) NULL,
    custrecord_4110_category               nvarchar(50) NULL,          -- tax category code (S0, ...)
    custrecord_4110_non_deductible         bit NULL,
    custrecord_4110_reverse_charge_alt     bit NULL,
    custrecord_4110_import                 bit NULL,
    custrecord_4110_reduced_rate           bit NULL,
    custrecord_4110_super_reduced          bit NULL,
    custrecord_4110_non_taxable            bit NULL,
    custrecord_4110_non_recoverable        bit NULL,
    custrecord_4110_partial_credit         bit NULL,
    custrecord_4110_no_tax_credit          bit NULL,
    custrecord_4110_capital_goods          bit NULL,
    custrecord_4110_duty                   bit NULL,
    custrecord_4110_electronic             bit NULL,
    custrecord_4110_government             bit NULL,
    custrecord_4110_non_operation          bit NULL,
    custrecord_4110_non_resident           bit NULL,
    custrecord_4110_other_tax_evidence     bit NULL,
    custrecord_4110_outside_customs        bit NULL,
    custrecord_4110_paid                   bit NULL,
    custrecord_4110_purchaser_issued       bit NULL,
    custrecord_4110_special_territory      bit NULL,
    custrecord_4110_surcharge              bit NULL,
    custrecord_4110_suspended              bit NULL,
    custrecord_4110_triplicate             bit NULL,
    custrecord_4110_unknown_tax_credit     bit NULL,
    custrecord_4110_cash_register          bit NULL,
    custrecord_4110_duplicate              bit NULL,
    custrecord_4110_no_tax_invoice         bit NULL,
    custrecord_100_percent_non_deductable  bit NULL,
    custrecord_deemed_supply               bit NULL,
    custrecord_for_digital_services        bit NULL,
    custrecord_is_direct_cost_service      bit NULL,
    custrecord_post_notional_tax_amount    bit NULL,
    custrecord_gcc_state                   bit NULL,
    CONSTRAINT PK_tb_Netsuite_SalesTaxItem PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_SalesTaxItem_id ON dbo.tb_Netsuite_SalesTaxItem (id);
CREATE NONCLUSTERED INDEX IX_tb_Netsuite_SalesTaxItem_BPA_Status ON dbo.tb_Netsuite_SalesTaxItem (BPA_Status, BPA_Direction) INCLUDE (id, BPA_Company);
PRINT N'Created  dbo.tb_Netsuite_SalesTaxItem';

-- ---------------------------------------------------------------------------
-- account
-- ---------------------------------------------------------------------------
EXEC #rebuild N'tb_NetSuite_Account';
CREATE TABLE dbo.tb_NetSuite_Account (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                           nvarchar(50) NULL,
    BPA_Direction                        nvarchar(50) NULL,
    BPA_Company                          nvarchar(50) NULL,
    BPA_EntryID                          uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Account_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                         uniqueidentifier NULL,
    BPA_Status                           int NULL CONSTRAINT DF_tb_NetSuite_Account_Status DEFAULT ((0)),
    BPA_Reference                        nvarchar(50) NULL,
    BPA_Reference_Description            nvarchar(100) NULL,
    BPA_Reference2                       nvarchar(50) NULL,
    BPA_Reference2_Description           nvarchar(100) NULL,
    BPA_Action                           nvarchar(1) NULL,
    BPA_ReturnedID                       nvarchar(50) NULL,
    BPA_Syscreated                       datetime NULL CONSTRAINT DF_tb_NetSuite_Account_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified                      datetime NULL CONSTRAINT DF_tb_NetSuite_Account_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator                       nvarchar(50) NULL,
    BPA_Error                            nvarchar(max) NULL,
    BPA_Error_Extended                   nvarchar(max) NULL,
    BPA_Description                      nvarchar(255) NULL,
    BPA_Failcount                        int NULL CONSTRAINT DF_tb_NetSuite_Account_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid                     uniqueidentifier NULL,
    BPA_TaskInstanceID                   int NULL,
    BPA_TaskID                           int NULL,

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    id                                   nvarchar(100) NOT NULL,
    externalId                           nvarchar(100) NULL,
    acctNumber                           nvarchar(60) NULL,
    acctName                             nvarchar(255) NULL,
    fullName                             nvarchar(1000) NULL,        -- number + name with parents
    displayNameWithHierarchy             nvarchar(1000) NULL,
    description                          nvarchar(1000) NULL,
    acctTypeId                           nvarchar(50) NULL,          -- AcctRec, Expense, ...
    acctTypeRefName                      nvarchar(100) NULL,
    sSpecAcctId                          nvarchar(50) NULL,          -- special account type
    sSpecAcctRefName                     nvarchar(100) NULL,
    parentId                             nvarchar(100) NULL,
    parentRefName                        nvarchar(400) NULL,
    currencyId                           nvarchar(100) NULL,         -- bank / credit card accounts
    currencyRefName                      nvarchar(400) NULL,
    generalRateId                        nvarchar(50) NULL,          -- CURRENT / HISTORICAL / AVERAGE
    generalRateRefName                   nvarchar(100) NULL,
    cashFlowRateId                       nvarchar(50) NULL,          -- CURRENT / HISTORICAL / AVERAGE
    cashFlowRateRefName                  nvarchar(100) NULL,
    isSummary                            bit NULL,
    inventory                            bit NULL,
    revalue                              bit NULL,
    eliminate                            bit NULL,
    reconcileWithMatching                bit NULL,
    balance                              decimal(19,4) NULL,         -- snapshot at load time
    includeChildren                      bit NULL,                   -- also valid for child subsidiaries
    departmentId                         nvarchar(100) NULL,         -- restrict to
    departmentRefName                    nvarchar(400) NULL,
    classId                              nvarchar(100) NULL,         -- restrict to
    classRefName                         nvarchar(400) NULL,
    locationId                           nvarchar(100) NULL,         -- restrict to
    locationRefName                      nvarchar(400) NULL,
    isInactive                           bit NULL,
    lastModifiedDate                     datetime2(0) NULL,          -- UTC
    custrecord_acct_bank_account_number  nvarchar(100) NULL,
    CONSTRAINT PK_tb_NetSuite_Account PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Account_id ON dbo.tb_NetSuite_Account (id) INCLUDE (lastModifiedDate);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Account_BPA_Status ON dbo.tb_NetSuite_Account (BPA_Status, BPA_Direction) INCLUDE (id, BPA_Company);
PRINT N'Created  dbo.tb_NetSuite_Account';

-- account/subsidiary/items -> dbo.tb_NetSuite_Account_Subsidiary: one row per selected subsidiary
EXEC #rebuild N'tb_NetSuite_Account_Subsidiary';
CREATE TABLE dbo.tb_NetSuite_Account_Subsidiary (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                  nvarchar(50) NULL,
    BPA_Direction               nvarchar(50) NULL,
    BPA_Company                 nvarchar(50) NULL,
    BPA_EntryID                 uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Account_Subsidiary_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                uniqueidentifier NULL,
    BPA_Status                  int NULL CONSTRAINT DF_tb_NetSuite_Account_Subsidiary_Status DEFAULT ((0)),
    BPA_Reference               nvarchar(50) NULL,
    BPA_Reference_Description   nvarchar(100) NULL,
    BPA_Reference2              nvarchar(50) NULL,
    BPA_Reference2_Description  nvarchar(100) NULL,
    BPA_Action                  nvarchar(1) NULL,
    BPA_ReturnedID              nvarchar(50) NULL,
    BPA_Syscreated              datetime NULL CONSTRAINT DF_tb_NetSuite_Account_Subsidiary_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified             datetime NULL CONSTRAINT DF_tb_NetSuite_Account_Subsidiary_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator              nvarchar(50) NULL,
    BPA_Error                   nvarchar(max) NULL,
    BPA_Error_Extended          nvarchar(max) NULL,
    BPA_Description             nvarchar(255) NULL,
    BPA_Failcount               int NULL CONSTRAINT DF_tb_NetSuite_Account_Subsidiary_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid            uniqueidentifier NULL,
    BPA_TaskInstanceID          int NULL,
    BPA_TaskID                  int NULL,

    -- Parent: BPA_ParentID = tb_NetSuite_Account.BPA_EntryID
    accountId                   nvarchar(100) NOT NULL,     -- account/id (the parent's NetSuite id)

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    subsidiaryId                nvarchar(100) NULL,
    subsidiaryRefName           nvarchar(400) NULL,
    CONSTRAINT PK_tb_NetSuite_Account_Subsidiary PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Account_Subsidiary_BPA_ParentID ON dbo.tb_NetSuite_Account_Subsidiary (BPA_ParentID);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Account_Subsidiary_accountId ON dbo.tb_NetSuite_Account_Subsidiary (accountId, subsidiaryId);
PRINT N'Created  dbo.tb_NetSuite_Account_Subsidiary';

-- ---------------------------------------------------------------------------
-- subsidiary
-- ---------------------------------------------------------------------------
EXEC #rebuild N'tb_NetSuite_Subsidiary';
CREATE TABLE dbo.tb_NetSuite_Subsidiary (
    -- BPA control fields (standard block, same as the other tb_Netsuite_* tables)
    BPA_Origin                   nvarchar(50) NULL,
    BPA_Direction                nvarchar(50) NULL,
    BPA_Company                  nvarchar(50) NULL,
    BPA_EntryID                  uniqueidentifier NOT NULL CONSTRAINT DF_tb_NetSuite_Subsidiary_EntryID DEFAULT (newsequentialid()),
    BPA_ParentID                 uniqueidentifier NULL,
    BPA_Status                   int NULL CONSTRAINT DF_tb_NetSuite_Subsidiary_Status DEFAULT ((0)),
    BPA_Reference                nvarchar(50) NULL,
    BPA_Reference_Description    nvarchar(100) NULL,
    BPA_Reference2               nvarchar(50) NULL,
    BPA_Reference2_Description   nvarchar(100) NULL,
    BPA_Action                   nvarchar(1) NULL,
    BPA_ReturnedID               nvarchar(50) NULL,
    BPA_Syscreated               datetime NULL CONSTRAINT DF_tb_NetSuite_Subsidiary_Syscreated DEFAULT (getdate()),
    BPA_Sysmodified              datetime NULL CONSTRAINT DF_tb_NetSuite_Subsidiary_Sysmodified DEFAULT (getdate()),
    BPA_Syscreator               nvarchar(50) NULL,
    BPA_Error                    nvarchar(max) NULL,
    BPA_Error_Extended           nvarchar(max) NULL,
    BPA_Description              nvarchar(255) NULL,
    BPA_Failcount                int NULL CONSTRAINT DF_tb_NetSuite_Subsidiary_Failcount DEFAULT ((0)),
    BPA_Orig_Entryid             uniqueidentifier NULL,
    BPA_TaskInstanceID           int NULL,
    BPA_TaskID                   int NULL,

    -- NetSuite fields (REST names; a reference is <field>Id + <field>RefName)
    id                           nvarchar(100) NOT NULL,
    externalId                   nvarchar(100) NULL,
    name                         nvarchar(255) NULL,
    fullName                     nvarchar(1000) NULL,        -- Parent : Child
    legalName                    nvarchar(255) NULL,
    parentId                     nvarchar(100) NULL,
    parentRefName                nvarchar(400) NULL,
    isElimination                bit NULL,
    countryId                    nvarchar(10) NULL,
    countryRefName               nvarchar(100) NULL,
    state                        nvarchar(100) NULL,
    currencyId                   nvarchar(100) NULL,         -- base currency
    currencyRefName              nvarchar(400) NULL,
    editionId                    nvarchar(10) NULL,          -- UK, NL, BE, ...
    editionRefName               nvarchar(100) NULL,
    federalIdNumber              nvarchar(50) NULL,          -- VAT / tax registration number
    email                        nvarchar(255) NULL,
    fax                          nvarchar(50) NULL,
    url                          nvarchar(400) NULL,
    tranPrefix                   nvarchar(50) NULL,
    fiscalCalendarId             nvarchar(100) NULL,
    fiscalCalendarRefName        nvarchar(400) NULL,
    representingVendorId         nvarchar(100) NULL,         -- intercompany vendor
    representingVendorRefName    nvarchar(400) NULL,
    representingCustomerId       nvarchar(100) NULL,         -- intercompany customer
    representingCustomerRefName  nvarchar(400) NULL,
    isInactive                   bit NULL,
    lastModifiedDate             datetime2(0) NULL,          -- UTC
    CONSTRAINT PK_tb_NetSuite_Subsidiary PRIMARY KEY CLUSTERED (BPA_EntryID)
);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Subsidiary_id ON dbo.tb_NetSuite_Subsidiary (id) INCLUDE (lastModifiedDate);
CREATE NONCLUSTERED INDEX IX_tb_NetSuite_Subsidiary_BPA_Status ON dbo.tb_NetSuite_Subsidiary (BPA_Status, BPA_Direction) INCLUDE (id, BPA_Company);
PRINT N'Created  dbo.tb_NetSuite_Subsidiary';

COMMIT TRANSACTION;
GO
DROP PROCEDURE #rebuild;
GO
